package com.chrono.chrono.services.pms;
import com.chrono.chrono.dto.pms.BillingProfile;
import com.chrono.chrono.entities.pms.*;
import com.chrono.chrono.repositories.pms.*;
import org.junit.jupiter.api.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.nio.charset.StandardCharsets;
import java.util.List;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
class PmsStructuredInvoiceServiceTest {
 PmsInvoiceLineRepository lines=mock(PmsInvoiceLineRepository.class);PmsInternationalSettingsService settings=mock(PmsInternationalSettingsService.class);PmsUblSchemaValidator validator=new PmsUblSchemaValidator();
 PmsStructuredInvoiceService service=new PmsStructuredInvoiceService(mock(PmsInvoiceRepository.class),lines,mock(HotelPropertyRepository.class),mock(PmsPropertyAccessService.class),settings,validator,mock(PmsAuditWriter.class),mock(jakarta.persistence.EntityManager.class));
 PmsInvoice invoice;PmsInvoiceLine line;
 @BeforeEach void setup(){HotelProperty hotel=new HotelProperty();org.springframework.test.util.ReflectionTestUtils.setField(hotel,"id",1L);hotel.setCurrencyCode("CHF");invoice=new PmsInvoice();invoice.setId(1L);invoice.setProperty(hotel);invoice.setInvoiceNumber("CH-001");invoice.setIssueDate(LocalDate.of(2026,9,12));invoice.setDueDate(LocalDate.of(2026,9,22));invoice.setServiceFrom(invoice.getIssueDate());invoice.setServiceTo(invoice.getIssueDate());invoice.setCurrencyCode("CHF");invoice.setNetAmount(new BigDecimal("100"));invoice.setVatAmount(new BigDecimal("10"));invoice.setGrossAmount(new BigDecimal("110"));invoice.setSupplierSnapshot(PmsProfileData.encode(party("Hotel & Partner","CHE123")));invoice.setRecipientSnapshot(PmsProfileData.encode(party("Guest <Example>",null)));line=new PmsInvoiceLine();line.setId(1L);line.setInvoice(invoice);line.setDescription("Room & breakfast");line.setQuantity(BigDecimal.ONE);line.setNetAmount(new BigDecimal("100"));line.setVatAmount(BigDecimal.TEN);line.setGrossAmount(new BigDecimal("110"));line.setVatRate(BigDecimal.TEN);line.setServiceDate(invoice.getIssueDate());when(lines.findAllByInvoice_IdOrderByIdAsc(1L)).thenReturn(List.of(line));when(settings.settings(hotel)).thenReturn(new PmsInternationalSettingsService.Settings(1L,0,"CH","CH-REGISTRATION","CH","test",List.of(),List.of(),"VAT",null,null,true));}
 BillingProfile party(String name,String vat){return new BillingProfile(name,null,"Street 1",null,"8000","Zürich",null,"CH",vat,"office@example.invalid",null,null,"COMPANY_FIRST","POSTAL_CITY",null);}
 @Test void generatesEscapedInvoiceAndPassesOfficialOasisSchema(){String xml=new String(service.generate(invoice,new PmsStructuredInvoiceService.Options(null,null)),StandardCharsets.UTF_8);assertThat(xml).contains("Hotel &amp; Partner","Guest &lt;Example&gt;","<cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode>").doesNotContain("#compliant#","urn:fdc:peppol");}
 @Test void creditNoteUsesPositiveCreditAmountsAndOriginalReference(){PmsInvoice original=new PmsInvoice();original.setInvoiceNumber("CH-ORIGINAL");original.setIssueDate(invoice.getIssueDate());invoice.setOriginalInvoice(original);invoice.setType(InvoiceType.CREDIT_NOTE);invoice.setNetAmount(invoice.getNetAmount().negate());invoice.setVatAmount(invoice.getVatAmount().negate());invoice.setGrossAmount(invoice.getGrossAmount().negate());line.setNetAmount(line.getNetAmount().negate());line.setVatAmount(line.getVatAmount().negate());line.setGrossAmount(line.getGrossAmount().negate());String xml=new String(service.generate(invoice,new PmsStructuredInvoiceService.Options(null,null)),StandardCharsets.UTF_8);assertThat(xml).contains("<CreditNote","CH-ORIGINAL","<cbc:CreditNoteTypeCode>381</cbc:CreditNoteTypeCode>").doesNotContain(">-100<",">-110<");}
 @Test void unknownZeroTaxTreatmentAndIncorrectTotalsAreRejected(){line.setVatRate(BigDecimal.ZERO);assertThatThrownBy(()->service.generate(invoice,new PmsStructuredInvoiceService.Options(null,null))).hasMessageContaining("Steuerkategorie");line.setVatRate(BigDecimal.TEN);invoice.setGrossAmount(new BigDecimal("111"));assertThatThrownBy(()->service.generate(invoice,new PmsStructuredInvoiceService.Options(null,null))).hasMessageContaining("Rechnungssummen");}
 @Test void missingHistoricalSellerIsNotFilledFromCurrentHotel(){invoice.setSupplierSnapshot(null);assertThatThrownBy(()->service.generate(invoice,new PmsStructuredInvoiceService.Options(null,null))).hasMessageContaining("Rechnungsaussteller");}
 @Test void schemaRejectsUnknownElementsAndExternalDtd(){assertThatThrownBy(()->validator.validate("<Invoice xmlns='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'><Fake/></Invoice>".getBytes(StandardCharsets.UTF_8),false)).hasMessageContaining("Schemaprüfung");assertThatThrownBy(()->validator.validate("<!DOCTYPE Invoice SYSTEM 'file:///C:/not-a-real-file'><Invoice xmlns='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'/>".getBytes(StandardCharsets.UTF_8),false)).hasMessageContaining("Schemaprüfung");}
}
