-- Cumulative schema baseline after V14.
-- New databases start here; existing databases continue to use V1 through V14.
-- Generated from the Hibernate entity model using the production MySQL dialect.

create table analytics_events (viewport_height integer, viewport_width integer, created_at datetime(6) not null, id bigint not null auto_increment, event_type varchar(32) not null, language varchar(32), session_id varchar(64), visitor_id varchar(64) not null, element_label varchar(160), page_title varchar(256), element_target varchar(512), path varchar(512) not null, referrer varchar(512), referrer_host varchar(255), primary key (id)) engine=InnoDB;
create table analytics_excluded_ips (created_at datetime(6) not null, id bigint not null auto_increment, ip_address varchar(45) not null, label varchar(120), primary key (id)) engine=InnoDB;
create table ap_vendor_invoices (amount decimal(19,4) not null, amount_paid decimal(19,4) not null, currency varchar(3), due_date date, invoice_date date, last_payment_date date, company_id bigint, id bigint not null auto_increment, journal_entry_id bigint, notes varchar(512), invoice_number varchar(255) not null, vendor_name varchar(255) not null, status enum ('CANCELLED','DRAFT','OPEN','PAID','PARTIALLY_PAID') not null, primary key (id)) engine=InnoDB;
create table ar_customer_invoices (amount decimal(19,4) not null, amount_paid decimal(19,4) not null, currency varchar(3), due_date date, invoice_date date, last_payment_date date, company_id bigint, id bigint not null auto_increment, journal_entry_id bigint, project_id bigint, notes varchar(512), customer_name varchar(255) not null, invoice_number varchar(255) not null, status enum ('CANCELLED','DRAFT','OPEN','PAID','PARTIALLY_PAID') not null, primary key (id)) engine=InnoDB;
create table bank_accounts (company_id bigint not null, id bigint not null auto_increment, bic varchar(255), clearing_number varchar(255), iban varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table bank_payment_batches (approved_at datetime(6), bank_account_id bigint not null, company_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, transmitted_at datetime(6), provider_artifact_path varchar(1024), provider_message varchar(1024), approval_by varchar(255), delivery_channel varchar(255), provider_artifact_name varchar(255), provider_status varchar(255), transmission_reference varchar(255), status enum ('APPROVED','DRAFT','FAILED','PENDING_APPROVAL','SENT') not null, primary key (id)) engine=InnoDB;
create table bank_payment_instructions (amount decimal(19,4) not null, currency varchar(3), batch_id bigint not null, customer_invoice_id bigint, id bigint not null auto_increment, vendor_invoice_id bigint, creditor_bic varchar(255), creditor_iban varchar(255), creditor_name varchar(255), reference varchar(255), primary key (id)) engine=InnoDB;
create table changelog (created_at datetime(6) not null, id bigint not null auto_increment, title varchar(255) not null, version varchar(255) not null, content text not null, primary key (id)) engine=InnoDB;
create table companies (active bit not null, canceled bit not null, canton_abbreviation varchar(2), custom_holiday_selection_enabled bit not null, customer_tracking_enabled bit, demo bit not null, demo_data_last_reset date, fak_rate float(53), ktg_rate_employee float(53), ktg_rate_employer float(53), midijob_factor float(53), notify_overtime bit, notify_vacation bit, paid bit not null, uvg_bu_rate float(53), uvg_nbu_rate float(53), demo_expires_at datetime(6), id bigint not null auto_increment, demo_session_id varchar(64), address_line1 varchar(255), address_line2 varchar(255), city varchar(255), logo_path varchar(255), name varchar(255), payment_method varchar(255), postal_code varchar(255), slack_webhook_url varchar(255), teams_webhook_url varchar(255), primary key (id)) engine=InnoDB;
create table company_enabled_features (company_id bigint not null, feature_key varchar(255)) engine=InnoDB;
create table company_holiday_preferences (half_day bit not null, company_id bigint not null, id bigint not null auto_increment, holiday_code varchar(80) not null, primary key (id)) engine=InnoDB;
create table company_knowledge (company_id bigint not null, id bigint not null auto_increment, title varchar(255) not null, access_level enum ('ADMIN_ONLY','ALL') not null, content tinytext not null, primary key (id)) engine=InnoDB;
create table compliance_audit_log (company_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, target_id bigint, details varchar(2000), action varchar(255) not null, target_type varchar(255) not null, username varchar(255) not null, severity enum ('CRITICAL','INFO','WARNING') not null, primary key (id)) engine=InnoDB;
create table correction_requests (approved bit not null, denied bit not null, request_date date, desired_timestamp datetime(6), id bigint not null auto_increment, target_entry_id bigint, user_id bigint not null, admin_comment varchar(1000), reason varchar(1000), desired_punch_type enum ('ENDE','START') not null, primary key (id)) engine=InnoDB;
create table crm_activities (contact_id bigint, customer_id bigint, id bigint not null auto_increment, timestamp datetime(6) not null, notes varchar(2048), owner varchar(255), type enum ('CALL','EMAIL','MEETING','NOTE','TASK') not null, primary key (id)) engine=InnoDB;
create table crm_campaigns (budget integer, end_date date, start_date date, company_id bigint not null, id bigint not null auto_increment, channel varchar(255), name varchar(255), status enum ('ACTIVE','ARCHIVED','COMPLETED','PLANNED') not null, primary key (id)) engine=InnoDB;
create table crm_customer_addresses (customer_id bigint not null, id bigint not null auto_increment, city varchar(255), country varchar(255), postal_code varchar(255), street varchar(255), type enum ('BILLING','OFFICE','SHIPPING') not null, primary key (id)) engine=InnoDB;
create table crm_customer_contacts (customer_id bigint not null, id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), phone varchar(255), role_title varchar(255), primary key (id)) engine=InnoDB;
create table crm_documents (customer_id bigint, id bigint not null auto_increment, uploaded_at datetime(6) not null, file_name varchar(255), uploaded_by varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
create table crm_leads (created_date date, company_id bigint not null, id bigint not null auto_increment, company_name varchar(255), contact_name varchar(255), email varchar(255), phone varchar(255), source varchar(255), status enum ('CONVERTED','DISQUALIFIED','NEW','QUALIFIED') not null, primary key (id)) engine=InnoDB;
create table crm_opportunities (expected_close_date date, opportunity_value decimal(19,4), probability float(53), company_id bigint not null, customer_id bigint, id bigint not null auto_increment, title varchar(255), stage enum ('LOST','NEGOTIATION','PROPOSAL','QUALIFICATION','WON') not null, primary key (id)) engine=InnoDB;
create table customers (company_id bigint not null, id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table daily_notes (note_date date not null, id bigint not null auto_increment, user_id bigint not null, content varchar(2000), primary key (id)) engine=InnoDB;
create table digital_signature_requests (company_id bigint, completed_at datetime(6), id bigint not null auto_increment, last_status_check datetime(6), requested_at datetime(6), provider_status_message varchar(1024), signing_url varchar(1024), document_path varchar(255), document_type varchar(255), provider_reference varchar(255), signer_email varchar(255), status enum ('COMPLETED','FAILED','IN_PROGRESS','PENDING') not null, primary key (id)) engine=InnoDB;
create table fa_assets (accumulated_depreciation decimal(19,4), acquisition_cost decimal(19,4) not null, acquisition_date date not null, last_depreciation_date date, residual_value decimal(19,4), useful_life_months integer not null, id bigint not null auto_increment, journal_entry_id bigint, asset_name varchar(255) not null, status enum ('ACTIVE','DISPOSED','FULLY_DEPRECIATED') not null, primary key (id)) engine=InnoDB;
create table gl_accounts (active bit not null, id bigint not null auto_increment, parent_id bigint, code varchar(32) not null, notes varchar(512), name varchar(255) not null, type enum ('ASSET','CONTRA_ASSET','EQUITY','EXPENSE','LIABILITY','OFF_BALANCE','REVENUE') not null, primary key (id)) engine=InnoDB;
create table gl_journal_entries (entry_date date not null, created_at datetime(6) not null, id bigint not null auto_increment, document_reference varchar(128), source varchar(128), description varchar(512), primary key (id)) engine=InnoDB;
create table gl_journal_entry_lines (credit decimal(19,4), debit decimal(19,4), account_id bigint not null, id bigint not null auto_increment, journal_entry_id bigint not null, memo varchar(256), primary key (id)) engine=InnoDB;
create table integration_configs (active bit not null, auto_sync bit not null, company_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, last_triggered_at datetime(6), updated_at datetime(6) not null, auth_header varchar(512), last_status varchar(1000), endpoint_url varchar(1024), name varchar(255) not null, type enum ('GENERIC_WEBHOOK','JIRA','MICROSOFT_TEAMS','SAP','SLACK') not null, primary key (id)) engine=InnoDB;
create table inv_cycle_counts (counted_quantity decimal(19,4), expected_quantity decimal(19,4) not null, variance decimal(19,4) not null, approved_at datetime(6), company_id bigint, counted_at datetime(6), created_at datetime(6) not null, id bigint not null auto_increment, product_id bigint not null, warehouse_id bigint not null, plan_number varchar(40) not null, approved_by varchar(120), counted_by varchar(120), requested_by varchar(120), status enum ('APPROVAL_REQUIRED','COMPLETED','PLANNED') not null, primary key (id)) engine=InnoDB;
create table inv_products (active bit not null, unit_cost decimal(19,4), unit_price decimal(19,4), company_id bigint, id bigint not null auto_increment, unit_of_measure varchar(32), description varchar(1024), name varchar(255) not null, sku varchar(255) not null, primary key (id)) engine=InnoDB;
create table inv_stock_levels (expiration_date date, quantity decimal(19,4) not null, reserved_quantity decimal(19,4) not null, id bigint not null auto_increment, product_id bigint not null, version bigint, warehouse_bin_id bigint, warehouse_id bigint not null, lot_number varchar(64), serial_number varchar(64), inventory_key varchar(320), inventory_status enum ('AVAILABLE','BLOCKED','DAMAGED','QUALITY_INSPECTION','QUARANTINE') not null, primary key (id)) engine=InnoDB;
create table inv_stock_movements (expiration_date date, quantity_change decimal(19,4) not null, id bigint not null auto_increment, movement_date datetime(6) not null, product_id bigint not null, warehouse_bin_id bigint, warehouse_id bigint not null, lot_number varchar(64), serial_number varchar(64), created_by varchar(120), reference varchar(128), idempotency_key varchar(160), notes varchar(512), inventory_status enum ('AVAILABLE','BLOCKED','DAMAGED','QUALITY_INSPECTION','QUARANTINE') not null, type enum ('ADJUSTMENT','GAIN','ISSUE','PRODUCTION_CONSUMPTION','PRODUCTION_OUTPUT','RECEIPT','TRANSFER','WRITE_OFF') not null, primary key (id)) engine=InnoDB;
create table inv_stock_reservations (quantity decimal(19,4) not null, company_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, sales_order_line_id bigint not null, stock_level_id bigint not null, updated_at datetime(6) not null, version bigint, created_by varchar(120), status enum ('ACTIVE','CONSUMED','RELEASED') not null, primary key (id)) engine=InnoDB;
create table inv_warehouse_bins (active bit not null, capacity_quantity decimal(19,4), pick_sequence integer not null, id bigint not null auto_increment, version bigint, warehouse_id bigint not null, aisle varchar(64), code varchar(64) not null, rack varchar(64), shelf varchar(64), zone varchar(64), barcode varchar(128), name varchar(160) not null, primary key (id)) engine=InnoDB;
create table inv_warehouses (company_id bigint, id bigint not null auto_increment, location varchar(512), code varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table mobile_app_feedback (app_version_code integer, company_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, user_id bigint, app_version_name varchar(40), app_menu_key varchar(80), app_menu_group varchar(120), app_menu_title varchar(120), username varchar(120) not null, display_name varchar(180), device_info varchar(300), message tinytext not null, primary key (id)) engine=InnoDB;
create table nfc_commands (created_at datetime(6), id bigint not null auto_increment, processed_at datetime(6), data varchar(255), status varchar(255), type varchar(255), primary key (id)) engine=InnoDB;
create table payslip_audit (id bigint not null auto_increment, payslip_id bigint, timestamp datetime(6) not null, action varchar(255) not null, author varchar(255) not null, comment varchar(255), primary key (id)) engine=InnoDB;
create table payslip_deductions (amount float(53), payslip_id bigint not null, type varchar(255)) engine=InnoDB;
create table payslip_earnings (amount float(53), payslip_id bigint not null, type varchar(255)) engine=InnoDB;
create table payslip_employer_contribs (amount float(53), payslip_id bigint not null, type varchar(255)) engine=InnoDB;
create table payslip_schedules (day_of_month integer, next_run date, id bigint not null auto_increment, user_id bigint, primary key (id)) engine=InnoDB;
create table payslips (allowances float(53), approved bit not null, bonuses float(53), deductions float(53), employer_contributions float(53), gross_salary float(53), locked bit not null, net_salary float(53), one_time_payments float(53), overtime_hours float(53), payout_date date, payout_overtime bit not null, period_end date, period_start date, tax_free_allowances float(53), version integer, id bigint not null auto_increment, user_id bigint, bank_account varchar(255), pay_type varchar(255), pdf_path varchar(255), social_security_number varchar(255), primary key (id)) engine=InnoDB;
create table pms_audit_events (company_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, property_id bigint not null, aggregate_type varchar(50) not null, integrity_hash varchar(64) not null, aggregate_id varchar(80) not null, event_type varchar(80) not null, actor varchar(120) not null, details varchar(4000) not null, primary key (id)) engine=InnoDB;
create table pms_cash_shifts (actual_cash decimal(12,2), expected_cash decimal(12,2), opening_float decimal(12,2) not null, variance decimal(12,2), closed_at datetime(6), id bigint not null auto_increment, opened_at datetime(6) not null, property_id bigint not null, closed_by varchar(120), opened_by varchar(120) not null, notes varchar(500), status enum ('CLOSED','OPEN') not null, primary key (id)) engine=InnoDB;
create table pms_channel_connections (id bigint not null auto_increment, last_sync_at datetime(6), property_id bigint not null, provider_code varchar(60) not null, display_name varchar(120) not null, secret_reference varchar(180), last_sync_message varchar(500), environment enum ('LIVE','SANDBOX') not null, status enum ('DISABLED','ERROR','READY','SYNCING') not null, primary key (id)) engine=InnoDB;
create table pms_channel_mappings (active bit not null, connection_id bigint not null, id bigint not null auto_increment, rate_plan_id bigint not null, room_type_id bigint not null, external_rate_code varchar(100) not null, external_room_code varchar(100) not null, primary key (id)) engine=InnoDB;
create table pms_communication_templates (active bit not null, id bigint not null auto_increment, language_code varchar(8) not null, property_id bigint not null, code varchar(40) not null, name varchar(180) not null, subject varchar(240) not null, body varchar(8000) not null, primary key (id)) engine=InnoDB;
create table pms_external_booking_references (id bigint not null auto_increment, property_id bigint not null, received_at datetime(6) not null, reservation_id bigint not null, channel_code varchar(50) not null, external_id varchar(160) not null, primary key (id)) engine=InnoDB;
create table pms_folio_items (quantity decimal(10,2) not null, service_date date not null, total_amount decimal(12,2) not null, unit_price decimal(12,2) not null, created_at datetime(6) not null, folio_id bigint not null, id bigint not null auto_increment, description varchar(240) not null, type enum ('BREAKFAST','DISCOUNT','OTHER','ROOM','SERVICE','TAX') not null, primary key (id)) engine=InnoDB;
create table pms_folios (currency_code varchar(3) not null, closed_at datetime(6), created_at datetime(6) not null, id bigint not null auto_increment, organization_id bigint, reservation_id bigint not null, label varchar(120) not null, status enum ('CLOSED','OPEN') not null, primary key (id)) engine=InnoDB;
create table pms_group_bookings (arrival_date date not null, departure_date date not null, contact_guest_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, organization_id bigint, property_id bigint not null, group_code varchar(40) not null, name varchar(180) not null, notes varchar(2000), status enum ('CANCELLED','COMPLETED','CONFIRMED','IN_HOUSE','OPTION') not null, primary key (id)) engine=InnoDB;
create table pms_guest_communications (created_at datetime(6) not null, guest_id bigint not null, id bigint not null auto_increment, property_id bigint not null, read_at datetime(6), reservation_id bigint, sent_at datetime(6), external_thread_id varchar(190), recipient varchar(190) not null, sender varchar(190), subject varchar(240) not null, body varchar(8000) not null, channel enum ('EMAIL','OTA','PORTAL','SMS','WHATSAPP') not null, direction enum ('INBOUND','OUTBOUND') not null, status enum ('DRAFT','FAILED','QUEUED','RECEIVED','SENT') not null, primary key (id)) engine=InnoDB;
create table pms_guest_registrations (country_code varchar(2), document_last_four varchar(4), nationality_code varchar(2), rule_version integer not null, completed_at datetime(6), expires_at datetime(6), id bigint not null auto_increment, invited_at datetime(6), privacy_consent_at datetime(6), reservation_id bigint not null, postal_code varchar(20), vehicle_plate varchar(32), rule_code varchar(40), document_hash varchar(64), token_hash varchar(64), city varchar(120), completed_by varchar(120), invited_by varchar(120), address_line varchar(180), signature_name varchar(180), status enum ('COMPLETED','PENDING') not null, primary key (id)) engine=InnoDB;
create table pms_guests (date_of_birth date, nationality_code varchar(2), vip bit not null, company_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, language_code varchar(8) not null, updated_at datetime(6) not null, phone varchar(60), first_name varchar(100) not null, last_name varchar(100) not null, email varchar(190), notes varchar(1000), primary key (id)) engine=InnoDB;
create table pms_hotel_resources (active bit not null, capacity integer not null, currency_code varchar(3) not null, hourly_rate decimal(12,2) not null, id bigint not null auto_increment, property_id bigint not null, code varchar(40) not null, location varchar(160), name varchar(160) not null, type enum ('BAR','CONFERENCE_ROOM','EQUIPMENT','OTHER','PARKING','RESTAURANT','SPA') not null, primary key (id)) engine=InnoDB;
create table pms_housekeeping_tasks (estimated_minutes integer not null, priority integer not null, service_date date not null, completed_at datetime(6), id bigint not null auto_increment, property_id bigint not null, room_id bigint not null, assigned_to varchar(120), notes varchar(1000), status enum ('CLEAN','DIRTY','INSPECTION','IN_PROGRESS','OUT_OF_SERVICE') not null, type enum ('ARRIVAL','DEPARTURE','INSPECTION','MANUAL','STAYOVER') not null, primary key (id)) engine=InnoDB;
create table pms_integration_outbox (attempt_count integer not null, created_at datetime(6) not null, delivered_at datetime(6), id bigint not null auto_increment, last_attempt_at datetime(6), locked_at datetime(6), next_attempt_at datetime(6), property_id bigint not null, aggregate_type varchar(50) not null, aggregate_id varchar(80) not null, event_type varchar(80) not null, lock_owner varchar(120), last_error varchar(1000), payload varchar(8000) not null, status enum ('DEAD_LETTER','DELIVERED','FAILED','PENDING','PROCESSING') not null, primary key (id)) engine=InnoDB;
create table pms_invoice_lines (gross_amount decimal(12,2) not null, net_amount decimal(12,2) not null, quantity decimal(10,2) not null, vat_amount decimal(12,2) not null, id bigint not null auto_increment, invoice_id bigint not null, description varchar(240) not null, primary key (id)) engine=InnoDB;
create table pms_invoices (currency_code varchar(3) not null, due_date date not null, gross_amount decimal(12,2) not null, issue_date date not null, net_amount decimal(12,2) not null, recipient_country_code varchar(2) not null, vat_amount decimal(12,2) not null, vat_rate decimal(5,2) not null, corrected_at datetime(6), created_at datetime(6) not null, folio_id bigint not null, id bigint not null auto_increment, original_invoice_id bigint, property_id bigint not null, recipient_postal_code varchar(20), qr_reference varchar(27), creditor_iban varchar(34), invoice_number varchar(50) not null, corrected_by varchar(120), recipient_city varchar(120), recipient_address varchar(180), recipient_name varchar(180) not null, correction_reason varchar(500), status enum ('CANCELLED','CREDITED','DRAFT','ISSUED','PAID') not null, type enum ('CREDIT_NOTE','INVOICE') not null, primary key (id)) engine=InnoDB;
create table pms_maintenance_work_orders (due_date date, id bigint not null auto_increment, property_id bigint not null, reported_at datetime(6) not null, resolved_at datetime(6), room_block_id bigint, room_id bigint not null, assigned_to varchar(120), reported_by varchar(120) not null, resolved_by varchar(120), title varchar(180) not null, description varchar(2000), resolution_notes varchar(2000), priority enum ('CRITICAL','HIGH','LOW','NORMAL') not null, status enum ('CANCELLED','IN_PROGRESS','OPEN','RESOLVED') not null, primary key (id)) engine=InnoDB;
create table pms_night_audits (business_date date not null, open_balance decimal(12,2) not null, arrivals_count bigint not null, closed_at datetime(6) not null, departures_count bigint not null, id bigint not null auto_increment, in_house_count bigint not null, no_show_count bigint not null, property_id bigint not null, closed_by varchar(120) not null, primary key (id)) engine=InnoDB;
create table pms_organizations (active bit not null, country_code varchar(2) not null, payment_terms_days integer not null, company_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, postal_code varchar(20), vat_number varchar(40), phone varchar(60), city varchar(120), address_line_1 varchar(180), name varchar(180) not null, billing_email varchar(190), email varchar(190), notes varchar(1000), type enum ('COMPANY','EVENT_ORGANIZER','TRAVEL_AGENCY') not null, primary key (id)) engine=InnoDB;
create table pms_payments (amount decimal(12,2) not null, folio_id bigint not null, id bigint not null auto_increment, original_payment_id bigint, received_at datetime(6) not null, voided_at datetime(6), created_by varchar(120) not null, reference varchar(120), voided_by varchar(120), reason varchar(500), kind enum ('PAYMENT','REFUND') not null, method enum ('BANK_TRANSFER','CARD','CASH','OTHER','VOUCHER') not null, status enum ('POSTED','VOIDED') not null, primary key (id)) engine=InnoDB;
create table pms_properties (active bit not null, check_in_time time(6) not null, check_out_time time(6) not null, country_code varchar(2) not null, currency_code varchar(3) not null, company_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, postal_code varchar(20), code varchar(32) not null, phone varchar(60), timezone varchar(64) not null, city varchar(120), name varchar(160) not null, address_line_1 varchar(180), legal_name varchar(180), email varchar(190), primary key (id)) engine=InnoDB;
create table pms_rate_overrides (closed bit not null, closed_arrival bit not null, closed_departure bit not null, min_stay integer not null, price decimal(12,2) not null, stay_date date not null, id bigint not null auto_increment, rate_plan_id bigint not null, primary key (id)) engine=InnoDB;
create table pms_rate_plans (active bit not null, breakfast_included bit not null, currency_code varchar(3) not null, min_stay integer not null, nightly_rate decimal(12,2) not null, refundable bit not null, id bigint not null auto_increment, property_id bigint not null, room_type_id bigint not null, code varchar(32) not null, name varchar(120) not null, primary key (id)) engine=InnoDB;
create table pms_reservation_status_history (changed_at datetime(6) not null, id bigint not null auto_increment, reservation_id bigint not null, changed_by varchar(120) not null, reason varchar(500), from_status enum ('CANCELLED','CHECKED_IN','CHECKED_OUT','CONFIRMED','NO_SHOW','OFFERED','TENTATIVE','WAITLISTED'), to_status enum ('CANCELLED','CHECKED_IN','CHECKED_OUT','CONFIRMED','NO_SHOW','OFFERED','TENTATIVE','WAITLISTED') not null, primary key (id)) engine=InnoDB;
create table pms_reservations (adults integer not null, arrival_date date not null, children integer not null, currency_code varchar(3) not null, departure_date date not null, total_amount decimal(12,2) not null, cancelled_at datetime(6), checked_in_at datetime(6), checked_out_at datetime(6), created_at datetime(6) not null, group_booking_id bigint, guest_id bigint not null, hold_until datetime(6), id bigint not null auto_increment, no_show_at datetime(6), property_id bigint not null, rate_plan_id bigint not null, room_id bigint, room_type_id bigint not null, updated_at datetime(6) not null, version bigint not null, confirmation_code varchar(40) not null, created_by varchar(120) not null, cancellation_reason varchar(500), notes varchar(2000), guarantee_status enum ('COMPANY_GUARANTEE','CREDIT_CARD','DEPOSIT_PAID','DEPOSIT_REQUIRED','OTA_GUARANTEE','UNGUARANTEED') not null, source enum ('BOOKING_ENGINE','CHANNEL_MANAGER','DIRECT','EMAIL','PHONE','WALK_IN') not null, status enum ('CANCELLED','CHECKED_IN','CHECKED_OUT','CONFIRMED','NO_SHOW','OFFERED','TENTATIVE','WAITLISTED') not null, primary key (id)) engine=InnoDB;
create table pms_resource_bookings (attendees integer not null, total_amount decimal(12,2) not null, created_at datetime(6) not null, end_at datetime(6) not null, group_booking_id bigint, id bigint not null auto_increment, property_id bigint not null, resource_id bigint not null, start_at datetime(6) not null, created_by varchar(120) not null, organizer_name varchar(180) not null, title varchar(180) not null, notes varchar(2000), status enum ('CANCELLED','CONFIRMED','TENTATIVE') not null, primary key (id)) engine=InnoDB;
create table pms_room_blocks (end_date date not null, start_date date not null, created_at datetime(6) not null, id bigint not null auto_increment, property_id bigint not null, resolved_at datetime(6), room_id bigint not null, created_by varchar(120) not null, resolved_by varchar(120), reason varchar(500) not null, status enum ('ACTIVE','CANCELLED','COMPLETED') not null, type enum ('OUT_OF_ORDER','OUT_OF_SERVICE','OWNER_USE') not null, primary key (id)) engine=InnoDB;
create table pms_room_types (active bit not null, base_occupancy integer not null, bed_count integer not null, max_occupancy integer not null, sort_order integer not null, id bigint not null auto_increment, property_id bigint not null, code varchar(32) not null, bed_type varchar(60), name varchar(120) not null, description varchar(1000), primary key (id)) engine=InnoDB;
create table pms_rooms (active bit not null, id bigint not null auto_increment, property_id bigint not null, room_type_id bigint not null, floor varchar(40), room_number varchar(40) not null, housekeeping_section varchar(80), name varchar(120), housekeeping_status enum ('CLEAN','DIRTY','INSPECTION','IN_PROGRESS','OUT_OF_SERVICE') not null, operational_status enum ('INACTIVE','IN_SERVICE','OUT_OF_ORDER') not null, primary key (id)) engine=InnoDB;
create table projects (budget_minutes integer, hourly_rate decimal(10,2), customer_id bigint, id bigint not null auto_increment, parent_id bigint, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table read_access_audit (id bigint not null auto_increment, timestamp datetime(6), path varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, role_name varchar(255), primary key (id)) engine=InnoDB;
create table schedule_change_logs (schedule_date date not null, actor_user_id bigint, company_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, schedule_entry_id bigint, target_user_id bigint, action varchar(64) not null, shift varchar(120), actor_username varchar(160) not null, target_username varchar(160), details varchar(2000), actor_display_name varchar(255), target_display_name varchar(255), primary key (id)) engine=InnoDB;
create table schedule_entries (date date, id bigint not null auto_increment, user_id bigint, note varchar(1000), shift varchar(255), primary key (id)) engine=InnoDB;
create table schedule_rules (is_active bit not null, id bigint not null auto_increment, end_time varchar(255) not null, label varchar(255) not null, shift_key varchar(255) not null, start_time varchar(255) not null, primary key (id)) engine=InnoDB;
create table scm_production_orders (completion_date date, quantity decimal(19,4) not null, start_date date, company_id bigint, id bigint not null auto_increment, product_id bigint not null, order_number varchar(255) not null, status enum ('CANCELLED','COMPLETED','IN_PROGRESS','PLANNED') not null, primary key (id)) engine=InnoDB;
create table scm_purchase_order_lines (quantity decimal(19,4) not null, received_quantity decimal(19,4) not null, unit_cost decimal(19,4) not null, id bigint not null auto_increment, product_id bigint not null, purchase_order_id bigint not null, primary key (id)) engine=InnoDB;
create table scm_purchase_orders (expected_date date, order_date date, total_amount decimal(19,4), company_id bigint, id bigint not null auto_increment, order_number varchar(255) not null, vendor_name varchar(255) not null, status enum ('APPROVED','CANCELLED','DRAFT','PARTIALLY_RECEIVED','RECEIVED') not null, primary key (id)) engine=InnoDB;
create table scm_sales_order_lines (fulfilled_quantity decimal(19,4) not null, quantity decimal(19,4) not null, reserved_quantity decimal(19,4) not null, unit_price decimal(19,4) not null, id bigint not null auto_increment, product_id bigint not null, sales_order_id bigint not null, primary key (id)) engine=InnoDB;
create table scm_sales_orders (due_date date, order_date date, total_amount decimal(19,4), company_id bigint, id bigint not null auto_increment, project_id bigint, customer_name varchar(255) not null, order_number varchar(255) not null, status enum ('CANCELLED','CONFIRMED','DRAFT','FULFILLED','PARTIALLY_FULFILLED','RESERVED') not null, primary key (id)) engine=InnoDB;
create table scm_service_requests (closed_date date, opened_date date, company_id bigint, id bigint not null auto_increment, description varchar(2048), customer_name varchar(255) not null, subject varchar(255) not null, status enum ('CLOSED','IN_PROGRESS','OPEN','RESOLVED') not null, primary key (id)) engine=InnoDB;
create table secure_messages (delivered bit not null, company_id bigint not null, id bigint not null auto_increment, sent_at datetime(6) not null, provider_message varchar(1024), body varchar(2048), provider_reference varchar(255), provider_status varchar(255), recipient varchar(255), subject varchar(255), transport varchar(255), primary key (id)) engine=InnoDB;
create table sick_leaves (end_date date not null, half_day bit not null, reported_at date not null, start_date date not null, id bigint not null auto_increment, user_id bigint not null, comment varchar(500), primary key (id)) engine=InnoDB;
create table tasks (billable bit, budget_minutes integer, id bigint not null auto_increment, project_id bigint, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table time_tracking (break_end time(6), break_start time(6), corrected bit not null, daily_date date not null, work_end time(6), work_start time(6), id bigint not null auto_increment, user_id bigint not null, daily_note varchar(2000), primary key (id)) engine=InnoDB;
create table time_tracking_entries (approved bit not null, corrected_by_user bit not null, duration_minutes integer, customer_id bigint, entry_timestamp datetime(6) not null, id bigint not null auto_increment, project_id bigint, task_id bigint, user_id bigint not null, description varchar(1000), system_generated_note varchar(255), punch_type enum ('ENDE','START') not null, source enum ('ADMIN_CORRECTION','MANUAL_IMPORT','MANUAL_PUNCH','MIGRATION_V1_BREAK_END','MIGRATION_V1_BREAK_START','MIGRATION_V1_WORK_END','MIGRATION_V1_WORK_START','NFC_SCAN','SYSTEM_AUTO_END','USER_CORRECTION'), primary key (id)) engine=InnoDB;
create table user_audit (id bigint not null auto_increment, timestamp datetime(6), user_id bigint, field_name varchar(255), new_value varchar(255), old_value varchar(255), primary key (id)) engine=InnoDB;
create table user_employment_model_history (daily_work_hours float(53), effective_from date not null, expected_work_days integer, schedule_cycle integer, schedule_effective_date date, work_percentage integer, id bigint not null auto_increment, user_id bigint not null, model_type enum ('HOURLY','PERCENTAGE','STANDARD') not null, weekly_schedule TEXT, primary key (id)) engine=InnoDB;
create table user_holiday_options (holiday_date date not null, id bigint not null auto_increment, user_id bigint not null, holiday_handling_option enum ('DEDUCT_FROM_WEEKLY_TARGET','DO_NOT_DEDUCT_FROM_WEEKLY_TARGET','PENDING_DECISION') not null, primary key (id)) engine=InnoDB;
create table user_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
create table user_schedule_rules (day_of_week integer, repeat_interval_days integer, start_date date, id bigint not null auto_increment, user_id bigint, day_mode varchar(255), rule_type varchar(255), primary key (id)) engine=InnoDB;
create table users (annual_vacation_days integer, birth_date date, break_duration integer, children integer, church_tax bit, daily_work_hours float(53), deleted bit not null, demo bit not null, email_notifications bit not null, entry_date date, expected_work_days integer, gkv_additional_rate float(53), hourly_rate float(53), include_in_time_tracking bit not null, is_hourly bit not null, is_percentage bit not null, monthly_salary float(53), opt_out bit not null, schedule_cycle integer, schedule_effective_date date, tracking_balance_in_minutes integer not null, work_percentage integer, company_id bigint, demo_expires_at datetime(6), id bigint not null auto_increment, last_customer_id bigint, demo_session_id varchar(64), address varchar(255), admin_password varchar(255), bank_account varchar(255), canton varchar(255), civil_status varchar(255), color varchar(255), country varchar(255) not null, department varchar(255), email varchar(255), federal_state varchar(255), first_name varchar(255), health_insurance varchar(255), landline_phone varchar(255), last_name varchar(255), mobile_phone varchar(255), password varchar(255) not null, personnel_number varchar(255) not null, religion varchar(255), social_security_number varchar(255), tarif_code varchar(255), tax_class varchar(255), username varchar(255) not null, page_permissions TEXT, weekly_schedule TEXT, primary key (id)) engine=InnoDB;
create table vacation_requests (approved bit not null, company_vacation bit not null, denied bit not null, end_date date, half_day bit not null, overtime_deduction_minutes integer, start_date date, uses_overtime bit not null, id bigint not null auto_increment, user_id bigint, admin_note varchar(1000), primary key (id)) engine=InnoDB;
create index idx_analytics_created_type on analytics_events (created_at, event_type);
create index idx_analytics_path_created on analytics_events (path, created_at);
create index idx_analytics_visitor_created on analytics_events (visitor_id, created_at);
alter table analytics_excluded_ips add constraint idx_analytics_excluded_ip unique (ip_address);
alter table ap_vendor_invoices add constraint UK7pmbch6in0qj30q3hnpeuy1xe unique (invoice_number);
alter table ar_customer_invoices add constraint UK9l8d9bf4hgwm6nhfm8ovgs7cw unique (invoice_number);
alter table changelog add constraint UKq4k29d3igwdws4vaejcpksxj3 unique (version);
alter table company_holiday_preferences add constraint UKkxbmps6672kdiqn3rr13v61go unique (company_id, holiday_code);
create index idx_audit_company_created on compliance_audit_log (company_id, created_at);
alter table daily_notes add constraint UK3k4x0qrv8kklixyqrgb0el7uy unique (user_id, note_date);
alter table gl_accounts add constraint UK3j5taib3t5ac21n91xs64p0s2 unique (code);
create index idx_inv_cycle_counts_company on inv_cycle_counts (company_id);
alter table inv_cycle_counts add constraint uk_inv_cycle_counts_company_plan unique (company_id, plan_number);
create index idx_inv_products_company on inv_products (company_id);
alter table inv_products add constraint uk_inv_products_company_sku unique (company_id, sku);
create index idx_inv_stock_levels_warehouse_bin on inv_stock_levels (warehouse_id, warehouse_bin_id);
create index idx_inv_stock_levels_expiration on inv_stock_levels (expiration_date, inventory_status);
alter table inv_stock_levels add constraint uk_inv_stock_levels_inventory_key unique (product_id, warehouse_id, inventory_key);
create index idx_inv_stock_movements_product_date on inv_stock_movements (product_id, movement_date);
create index idx_inv_stock_movements_warehouse_date on inv_stock_movements (warehouse_id, movement_date);
create index idx_inv_stock_movements_bin on inv_stock_movements (warehouse_bin_id);
alter table inv_stock_movements add constraint uk_inv_stock_movements_idempotency unique (idempotency_key);
create index idx_inv_stock_reservations_company on inv_stock_reservations (company_id);
create index idx_inv_stock_reservations_order_line on inv_stock_reservations (sales_order_line_id, status);
create index idx_inv_stock_reservations_stock on inv_stock_reservations (stock_level_id, status);
create index idx_inv_warehouse_bins_warehouse on inv_warehouse_bins (warehouse_id);
create index idx_inv_warehouse_bins_zone_sequence on inv_warehouse_bins (warehouse_id, zone, pick_sequence);
alter table inv_warehouse_bins add constraint uk_inv_warehouse_bins_warehouse_code unique (warehouse_id, code);
alter table inv_warehouse_bins add constraint uk_inv_warehouse_bins_barcode unique (barcode);
create index idx_inv_warehouses_company on inv_warehouses (company_id);
alter table inv_warehouses add constraint uk_inv_warehouses_company_code unique (company_id, code);
create index idx_mobile_feedback_created on mobile_app_feedback (created_at);
create index idx_mobile_feedback_company_created on mobile_app_feedback (company_id, created_at);
create index idx_pms_audit_property_created on pms_audit_events (property_id, created_at);
create index idx_pms_audit_company_created on pms_audit_events (company_id, created_at);
create index idx_pms_cash_shift_property_status on pms_cash_shifts (property_id, status);
alter table pms_channel_connections add constraint uk_pms_channel_property_provider unique (property_id, provider_code);
alter table pms_channel_mappings add constraint uk_pms_channel_mapping_rate unique (connection_id, rate_plan_id);
alter table pms_communication_templates add constraint uk_pms_template_property_code unique (property_id, code);
create index idx_pms_external_booking_reservation on pms_external_booking_references (reservation_id);
alter table pms_external_booking_references add constraint uk_pms_external_booking_channel_id unique (property_id, channel_code, external_id);
alter table pms_external_booking_references add constraint UKhqtom7malh6padvi5mvr5mgov unique (reservation_id);
create index idx_pms_folio_item_folio on pms_folio_items (folio_id);
create index idx_pms_folio_reservation on pms_folios (reservation_id);
create index idx_pms_group_property_dates on pms_group_bookings (property_id, arrival_date, departure_date);
alter table pms_group_bookings add constraint uk_pms_group_property_code unique (property_id, group_code);
create index idx_pms_communication_property_status on pms_guest_communications (property_id, status);
alter table pms_guest_registrations add constraint uk_pms_guest_registration_reservation unique (reservation_id);
alter table pms_guest_registrations add constraint UKrhalhympeiju7k3wlbaen6hly unique (token_hash);
create index idx_pms_guest_company_name on pms_guests (company_id, last_name, first_name);
create index idx_pms_guest_company_email on pms_guests (company_id, email);
alter table pms_hotel_resources add constraint uk_pms_resource_property_code unique (property_id, code);
create index idx_pms_housekeeping_property_date on pms_housekeeping_tasks (property_id, service_date);
alter table pms_housekeeping_tasks add constraint uk_pms_housekeeping_room_date unique (room_id, service_date);
create index idx_pms_outbox_property_status on pms_integration_outbox (property_id, status, next_attempt_at, created_at);
alter table pms_invoices add constraint uk_pms_invoice_property_number unique (property_id, invoice_number);
create index idx_pms_maintenance_property_status on pms_maintenance_work_orders (property_id, status);
alter table pms_maintenance_work_orders add constraint UK43fhwsqg2y3jxs4j456mtgo12 unique (room_block_id);
alter table pms_night_audits add constraint uk_pms_night_audit_property_date unique (property_id, business_date);
create index idx_pms_organization_company_name on pms_organizations (company_id, name);
create index idx_pms_payment_folio on pms_payments (folio_id);
create index idx_pms_property_company on pms_properties (company_id);
alter table pms_properties add constraint uk_pms_property_company_code unique (company_id, code);
create index idx_pms_rate_override_date on pms_rate_overrides (rate_plan_id, stay_date);
alter table pms_rate_overrides add constraint uk_pms_rate_override_plan_date unique (rate_plan_id, stay_date);
create index idx_pms_rate_plan_property on pms_rate_plans (property_id);
create index idx_pms_rate_plan_room_type on pms_rate_plans (room_type_id);
alter table pms_rate_plans add constraint uk_pms_rate_plan_property_code unique (property_id, code);
create index idx_pms_reservation_status_history on pms_reservation_status_history (reservation_id, changed_at);
create index idx_pms_reservation_property_dates on pms_reservations (property_id, arrival_date, departure_date);
create index idx_pms_reservation_room_dates on pms_reservations (room_id, arrival_date, departure_date);
create index idx_pms_reservation_guest on pms_reservations (guest_id);
alter table pms_reservations add constraint uk_pms_reservation_confirmation unique (property_id, confirmation_code);
create index idx_pms_resource_booking_dates on pms_resource_bookings (resource_id, start_at, end_at);
create index idx_pms_room_block_room_dates on pms_room_blocks (room_id, start_date, end_date);
create index idx_pms_room_block_property_status on pms_room_blocks (property_id, status);
create index idx_pms_room_type_property on pms_room_types (property_id);
alter table pms_room_types add constraint uk_pms_room_type_property_code unique (property_id, code);
create index idx_pms_room_property on pms_rooms (property_id);
create index idx_pms_room_type on pms_rooms (room_type_id);
alter table pms_rooms add constraint uk_pms_room_property_number unique (property_id, room_number);
create index idx_schedule_change_company_date_created on schedule_change_logs (company_id, schedule_date, created_at);
create index idx_schedule_change_target_date on schedule_change_logs (target_user_id, schedule_date);
alter table schedule_entries add constraint uk_schedule_entries_user_date_shift unique (user_id, date, shift);
alter table schedule_rules add constraint UK2352n7exhkpcl1rtpd84ule3u unique (shift_key);
create index idx_scm_production_orders_company on scm_production_orders (company_id);
alter table scm_production_orders add constraint uk_scm_production_orders_company_number unique (company_id, order_number);
create index idx_scm_purchase_orders_company on scm_purchase_orders (company_id);
alter table scm_purchase_orders add constraint uk_scm_purchase_orders_company_number unique (company_id, order_number);
create index idx_scm_sales_orders_company on scm_sales_orders (company_id);
alter table scm_sales_orders add constraint uk_scm_sales_orders_company_number unique (company_id, order_number);
create index idx_scm_service_requests_company on scm_service_requests (company_id);
alter table time_tracking add constraint UK1c3i1wcf0yek2vb7nbqjapm01 unique (user_id, daily_date);
create index IDXqqdgwdwyt596k7sgc4a08jo8w on time_tracking_entries (user_id, entry_timestamp);
alter table user_holiday_options add constraint UKo8ljerj5ruaog8h1r3ks8pvsv unique (user_id, holiday_date);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table ap_vendor_invoices add constraint FKilsdkbgv2ifk1g26rydpqcgsj foreign key (company_id) references companies (id);
alter table ap_vendor_invoices add constraint FKslsitdshuev74iyctdij08ycd foreign key (journal_entry_id) references gl_journal_entries (id);
alter table ar_customer_invoices add constraint FK706xriihbj54xngq5x0bfxr8q foreign key (company_id) references companies (id);
alter table ar_customer_invoices add constraint FKgcwur1n9adv60iu2kb22d7g5r foreign key (journal_entry_id) references gl_journal_entries (id);
alter table bank_accounts add constraint FKdvnlbhowmkddn62i80sbmmtny foreign key (company_id) references companies (id);
alter table bank_payment_batches add constraint FKf76w06kqf1xn6ma9sgkf8d619 foreign key (bank_account_id) references bank_accounts (id);
alter table bank_payment_batches add constraint FKtck257jcpdbliaccqxch2xsnu foreign key (company_id) references companies (id);
alter table bank_payment_instructions add constraint FK85krv1h1jtbkhe2wf58e0lfum foreign key (batch_id) references bank_payment_batches (id);
alter table bank_payment_instructions add constraint FKm38pfdflsauqvjnwh4u9ed9ao foreign key (customer_invoice_id) references ar_customer_invoices (id);
alter table bank_payment_instructions add constraint FKhflde3sjjcpvtl1xlhw1lu27 foreign key (vendor_invoice_id) references ap_vendor_invoices (id);
alter table company_enabled_features add constraint FKm36iik2ne0prny3d5f1odhwcr foreign key (company_id) references companies (id);
alter table company_holiday_preferences add constraint FKgwn99ad69i8vllmvxm4gtqslm foreign key (company_id) references companies (id);
alter table company_knowledge add constraint FKqw9ji9qley05yq0l4rbfslx30 foreign key (company_id) references companies (id);
alter table compliance_audit_log add constraint FKke3q6jh2ifimgbvwa4djtni2v foreign key (company_id) references companies (id);
alter table correction_requests add constraint FKtm9o55ecqpqlweb256lis7mvt foreign key (target_entry_id) references time_tracking_entries (id);
alter table correction_requests add constraint FKmukxx4pwggirkpc47ssb4v6ix foreign key (user_id) references users (id);
alter table crm_activities add constraint FKqrifrw6wahrwqbxhsppqgfv7g foreign key (contact_id) references crm_customer_contacts (id);
alter table crm_activities add constraint FK42e7jv7qoewcdwurn4dh4k38c foreign key (customer_id) references customers (id);
alter table crm_campaigns add constraint FKhmhddhm0mpmdnumuts3g4vl6q foreign key (company_id) references companies (id);
alter table crm_customer_addresses add constraint FK34q8om42ye4ejlbrnrhwshjht foreign key (customer_id) references customers (id);
alter table crm_customer_contacts add constraint FK26cokxlt50q900isawravf8n4 foreign key (customer_id) references customers (id);
alter table crm_documents add constraint FKbh741tpf4rby0oar77bntmxri foreign key (customer_id) references customers (id);
alter table crm_leads add constraint FKiryw9a8t8sksb8nhocu3uyq82 foreign key (company_id) references companies (id);
alter table crm_opportunities add constraint FKd1gc63001mq8ngd2mcepg4t4d foreign key (company_id) references companies (id);
alter table crm_opportunities add constraint FKb1sbq9ns16dq4khb1nays6kbn foreign key (customer_id) references customers (id);
alter table customers add constraint FKl9seru5curo311xhtpbxe3074 foreign key (company_id) references companies (id);
alter table daily_notes add constraint FKahf5yek5f225ofnnfo6vln5y0 foreign key (user_id) references users (id);
alter table digital_signature_requests add constraint FKbsvlxjdj9s4lacmmfhmimwra0 foreign key (company_id) references companies (id);
alter table fa_assets add constraint FK9hsq84q8lfojvulehmbtclgwy foreign key (journal_entry_id) references gl_journal_entries (id);
alter table gl_accounts add constraint FKq7igoribb3kwq09jmuvcrffik foreign key (parent_id) references gl_accounts (id);
alter table gl_journal_entry_lines add constraint FKic6uub7xwfmywqle5ppyw5kac foreign key (account_id) references gl_accounts (id);
alter table gl_journal_entry_lines add constraint FK7d06mfeahj1tgdf1havdngv2b foreign key (journal_entry_id) references gl_journal_entries (id);
alter table integration_configs add constraint FKb1w4e9360u9j8ilyeryjmktcy foreign key (company_id) references companies (id);
alter table inv_cycle_counts add constraint FKcpipq397aifj88po1fkveajy7 foreign key (company_id) references companies (id);
alter table inv_cycle_counts add constraint FKa7p5yt5k7vjjbln3ss80a3yji foreign key (product_id) references inv_products (id);
alter table inv_cycle_counts add constraint FKjb3vsq99cxt09dmqhfimhtd04 foreign key (warehouse_id) references inv_warehouses (id);
alter table inv_products add constraint FKru3jtll4lets0qfluvegnk8av foreign key (company_id) references companies (id);
alter table inv_stock_levels add constraint FKdlgd7pnsvvdc7o201lw6tbksn foreign key (product_id) references inv_products (id);
alter table inv_stock_levels add constraint FK8lye7yf30mm2fhobd1bjgjlfk foreign key (warehouse_id) references inv_warehouses (id);
alter table inv_stock_levels add constraint FKnomso0ff3l79iv67edanfuugs foreign key (warehouse_bin_id) references inv_warehouse_bins (id);
alter table inv_stock_movements add constraint FKogqej7cs11vmpf635i2xqtdnh foreign key (product_id) references inv_products (id);
alter table inv_stock_movements add constraint FKl69jv9c7eq647h7je2s84uig0 foreign key (warehouse_id) references inv_warehouses (id);
alter table inv_stock_movements add constraint FK85r6vuufap9eyro9oman22wu8 foreign key (warehouse_bin_id) references inv_warehouse_bins (id);
alter table inv_stock_reservations add constraint FK7m17wev5kbs2pulnqvu3vaf03 foreign key (company_id) references companies (id);
alter table inv_stock_reservations add constraint FKm47c8sxv0q2ed2iekr90oegad foreign key (sales_order_line_id) references scm_sales_order_lines (id);
alter table inv_stock_reservations add constraint FKqmi21t3xlk2lwa2v1o59hppf6 foreign key (stock_level_id) references inv_stock_levels (id);
alter table inv_warehouse_bins add constraint FKmof95ebboyfnlq6gqrkj5fhpu foreign key (warehouse_id) references inv_warehouses (id);
alter table inv_warehouses add constraint FKhrma91alm6bwdc12a2f43np1p foreign key (company_id) references companies (id);
alter table mobile_app_feedback add constraint FK3iltyosi7tgeijeme0gcfui1r foreign key (company_id) references companies (id);
alter table mobile_app_feedback add constraint FK9d22t48oki3r9pl8oudnv9h6s foreign key (user_id) references users (id);
alter table payslip_audit add constraint FKondeo6g5wwv6khuu6k6nbtmi foreign key (payslip_id) references payslips (id);
alter table payslip_deductions add constraint FKqfql1tfjsxtxlxadwf5ttir2c foreign key (payslip_id) references payslips (id);
alter table payslip_earnings add constraint FK2d1koprik41bfjvfatj6fkaho foreign key (payslip_id) references payslips (id);
alter table payslip_employer_contribs add constraint FK65kliw9ihp0n7gep7rdsyduu1 foreign key (payslip_id) references payslips (id);
alter table payslip_schedules add constraint FK1hh7dja9nhtwgw2hlqd69o515 foreign key (user_id) references users (id);
alter table payslips add constraint FKc3j0otrqdsqy6qmu526pv4rl6 foreign key (user_id) references users (id);
alter table pms_audit_events add constraint FKc290r3ew6tu76wpyyqhs4y09y foreign key (company_id) references companies (id);
alter table pms_audit_events add constraint FKfu526j22jsy96x32ov8esr6ak foreign key (property_id) references pms_properties (id);
alter table pms_cash_shifts add constraint FKbccd8p0nlmoe4osx7m67fkays foreign key (property_id) references pms_properties (id);
alter table pms_channel_connections add constraint FKepucbab3rlcpglf05vssnf6u0 foreign key (property_id) references pms_properties (id);
alter table pms_channel_mappings add constraint FKberbquaestf058s8gd7iausjd foreign key (connection_id) references pms_channel_connections (id);
alter table pms_channel_mappings add constraint FK1yi5twd2mb27rna73rjqwh3tc foreign key (rate_plan_id) references pms_rate_plans (id);
alter table pms_channel_mappings add constraint FKtgkn0s1s1dnkop41x2gi2dk95 foreign key (room_type_id) references pms_room_types (id);
alter table pms_communication_templates add constraint FK8wdgl62ph680g4py0ggcrhwpp foreign key (property_id) references pms_properties (id);
alter table pms_external_booking_references add constraint FK87wkov04l0wucxk1ubri0uf5v foreign key (property_id) references pms_properties (id);
alter table pms_external_booking_references add constraint FKi2tsi8an5jbtd8mpx29jbe3se foreign key (reservation_id) references pms_reservations (id);
alter table pms_folio_items add constraint FK2sxqoqjl2rj94oh2b1muhl102 foreign key (folio_id) references pms_folios (id);
alter table pms_folios add constraint FKboabxs9td2daq1wmw8j76e16l foreign key (organization_id) references pms_organizations (id);
alter table pms_folios add constraint FKhghbwvi64tdsnrmvtplqghpya foreign key (reservation_id) references pms_reservations (id);
alter table pms_group_bookings add constraint FKq6ku6ej51lky6yu3dgsbq453i foreign key (contact_guest_id) references pms_guests (id);
alter table pms_group_bookings add constraint FK9w3f516e87rqa69sc7enekp3 foreign key (organization_id) references pms_organizations (id);
alter table pms_group_bookings add constraint FK2yilpdniouv8riasdnk59klb4 foreign key (property_id) references pms_properties (id);
alter table pms_guest_communications add constraint FKs6osi9tm9gy8l80ue5twj8bv0 foreign key (guest_id) references pms_guests (id);
alter table pms_guest_communications add constraint FKd0b75ggykuhiwpb9mc8vk49gk foreign key (property_id) references pms_properties (id);
alter table pms_guest_communications add constraint FKcl65usxp3c9c60nw27ahqqmmy foreign key (reservation_id) references pms_reservations (id);
alter table pms_guest_registrations add constraint FKbweesav8msq7yg0wqwjmal2d foreign key (reservation_id) references pms_reservations (id);
alter table pms_guests add constraint FK7pvoo6y18v7qeyk9skywrqbeu foreign key (company_id) references companies (id);
alter table pms_hotel_resources add constraint FKb0c7ga635avg7le7y49li490f foreign key (property_id) references pms_properties (id);
alter table pms_housekeeping_tasks add constraint FKk4mf9nr1in0ob68dcuvx3r0dq foreign key (property_id) references pms_properties (id);
alter table pms_housekeeping_tasks add constraint FKbq09gt2n2phiqrk9uoalt4r4m foreign key (room_id) references pms_rooms (id);
alter table pms_integration_outbox add constraint FKfbeeedt3chakck4e05ldnm894 foreign key (property_id) references pms_properties (id);
alter table pms_invoice_lines add constraint FKpi6aqatdl8p8bc72edeaoo1kr foreign key (invoice_id) references pms_invoices (id);
alter table pms_invoices add constraint FK85kmubrinmpm7ma3lhhl2fxi7 foreign key (folio_id) references pms_folios (id);
alter table pms_invoices add constraint FKh3sv5oqrm9pquemelwrsx2cc2 foreign key (original_invoice_id) references pms_invoices (id);
alter table pms_invoices add constraint FKhbwfjfk38vvisojid0tr5g22t foreign key (property_id) references pms_properties (id);
alter table pms_maintenance_work_orders add constraint FKnd6blg9iwqw5bca9ic25pi7he foreign key (property_id) references pms_properties (id);
alter table pms_maintenance_work_orders add constraint FKmovlu3ic363u1fljyoko9lt33 foreign key (room_id) references pms_rooms (id);
alter table pms_maintenance_work_orders add constraint FK6d7u6kc0n20ojmop9sxc5snsr foreign key (room_block_id) references pms_room_blocks (id);
alter table pms_night_audits add constraint FK1rdwwd61w1j2322rwc9wiuccm foreign key (property_id) references pms_properties (id);
alter table pms_organizations add constraint FK47rpcfajfrv8fy16ucqyvv734 foreign key (company_id) references companies (id);
alter table pms_payments add constraint FK908e2cerx8gyv376h6eb8jeix foreign key (folio_id) references pms_folios (id);
alter table pms_payments add constraint FK5fp2hq1k5q4f4vnmk45ncku6g foreign key (original_payment_id) references pms_payments (id);
alter table pms_properties add constraint FK2uhcodivcdfgamra73vifn2cm foreign key (company_id) references companies (id);
alter table pms_rate_overrides add constraint FK9d2qfmy1hlkj2lhon5pr2578k foreign key (rate_plan_id) references pms_rate_plans (id);
alter table pms_rate_plans add constraint FK54492fkgaodwyt7tt74dro0h8 foreign key (property_id) references pms_properties (id);
alter table pms_rate_plans add constraint FKpls0c27y66fsskk6veoqyxh5u foreign key (room_type_id) references pms_room_types (id);
alter table pms_reservation_status_history add constraint FKelk2u6ou6p2yyoc0xkmrp9qgp foreign key (reservation_id) references pms_reservations (id);
alter table pms_reservations add constraint FKby20wwchc5i24emdsunlpbpli foreign key (group_booking_id) references pms_group_bookings (id);
alter table pms_reservations add constraint FK5b60fkcnic418sejti5n7xvbx foreign key (guest_id) references pms_guests (id);
alter table pms_reservations add constraint FKg3l9o2vvov1ula2n2vrs28l8n foreign key (property_id) references pms_properties (id);
alter table pms_reservations add constraint FKg11dqaximyjw1bxkjw30cnivi foreign key (rate_plan_id) references pms_rate_plans (id);
alter table pms_reservations add constraint FKdg3irk2jpb7dbnecoy54prhnq foreign key (room_id) references pms_rooms (id);
alter table pms_reservations add constraint FK8s924q3qlmcvyhqqis4pgf8r5 foreign key (room_type_id) references pms_room_types (id);
alter table pms_resource_bookings add constraint FKl9foweeop70b46pxsj2a7pmfr foreign key (group_booking_id) references pms_group_bookings (id);
alter table pms_resource_bookings add constraint FKtj8hg2yyh9rupg8cwgaagt420 foreign key (property_id) references pms_properties (id);
alter table pms_resource_bookings add constraint FKcr8wg7xqjg43uisykd2dntotm foreign key (resource_id) references pms_hotel_resources (id);
alter table pms_room_blocks add constraint FK22j0qdhwk037kukdg0keq90n6 foreign key (property_id) references pms_properties (id);
alter table pms_room_blocks add constraint FKqsfcsqag61w8wotjlco1lg46k foreign key (room_id) references pms_rooms (id);
alter table pms_room_types add constraint FK1rig7s4jiqmnsompvint1b9o foreign key (property_id) references pms_properties (id);
alter table pms_rooms add constraint FK20nfkpf1ygsrc3phsew3amh2s foreign key (property_id) references pms_properties (id);
alter table pms_rooms add constraint FK4m75l0gkvpov1co48sn0v82mf foreign key (room_type_id) references pms_room_types (id);
alter table projects add constraint FK4rpwuljjwr5rygq9gwx36q8cj foreign key (customer_id) references customers (id);
alter table projects add constraint FKqixloat3pyattepk842yxy4a6 foreign key (parent_id) references projects (id);
alter table schedule_change_logs add constraint FKpr89qn4iirb9q2lk1tyhyypyr foreign key (actor_user_id) references users (id);
alter table schedule_change_logs add constraint FKlyi4l5n5ffaki6xfao2jvsswg foreign key (company_id) references companies (id);
alter table schedule_change_logs add constraint FK63g434exnuo6tnuo2ela0rvjy foreign key (target_user_id) references users (id);
alter table schedule_entries add constraint FK8dju7qu6977w3dts3qx31sn49 foreign key (user_id) references users (id);
alter table scm_production_orders add constraint FKyq6gewapivchqje6wko4ibyy foreign key (company_id) references companies (id);
alter table scm_production_orders add constraint FK43snwwn41g6bhmle4monq51v8 foreign key (product_id) references inv_products (id);
alter table scm_purchase_order_lines add constraint FKltmh361h460ygvh7vkwb7bh8r foreign key (product_id) references inv_products (id);
alter table scm_purchase_order_lines add constraint FKt1d0gyxestpn9uso8rmcv0ras foreign key (purchase_order_id) references scm_purchase_orders (id);
alter table scm_purchase_orders add constraint FKq3sobmxqmt5y3lalsqhe33e5j foreign key (company_id) references companies (id);
alter table scm_sales_order_lines add constraint FK85voe3swd7ik1l7avd28fsrwy foreign key (product_id) references inv_products (id);
alter table scm_sales_order_lines add constraint FKs7l3h4kwvup8vuejkdbjrhy68 foreign key (sales_order_id) references scm_sales_orders (id);
alter table scm_sales_orders add constraint FKjsy6tfmnrtwjtqkcp4hdxeh6n foreign key (company_id) references companies (id);
alter table scm_service_requests add constraint FKsddn5x14miuaqjx4tlcov5mur foreign key (company_id) references companies (id);
alter table secure_messages add constraint FKdspe6x76tjhgoifdn43v0m8me foreign key (company_id) references companies (id);
alter table sick_leaves add constraint FK207465jsg98jdcksrhxdhq7qb foreign key (user_id) references users (id);
alter table tasks add constraint FKsfhn82y57i3k9uxww1s007acc foreign key (project_id) references projects (id);
alter table time_tracking add constraint FKp3sph46jdfwn3rbowfq7ucsvf foreign key (user_id) references users (id);
alter table time_tracking_entries add constraint FKrb2ohahm4722hcskeu879m07s foreign key (customer_id) references customers (id);
alter table time_tracking_entries add constraint FKnwtfeiljecxl4ltr2mv1ggru5 foreign key (project_id) references projects (id);
alter table time_tracking_entries add constraint FK7lm1wjyudtiq9lm9ci0638ra1 foreign key (task_id) references tasks (id);
alter table time_tracking_entries add constraint FKqjw96exbcvccwpetnjn52lhcw foreign key (user_id) references users (id);
alter table user_audit add constraint FK94oi4sytagh91ioovcocwtwxq foreign key (user_id) references users (id);
alter table user_employment_model_history add constraint FKqp1eav74qlmg1aq65qvdqcj1x foreign key (user_id) references users (id);
alter table user_holiday_options add constraint FKt2m3op9y4hnr1c3vkillddtec foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
alter table user_schedule_rules add constraint FKe5vdq6fiipjji8t5epl13l0g3 foreign key (user_id) references users (id);
alter table users add constraint FKin8gn4o1hpiwe6qe4ey7ykwq7 foreign key (company_id) references companies (id);
alter table users add constraint FKkbxevlwbqjq2v5y2ps1dg9j4a foreign key (last_customer_id) references customers (id);
alter table vacation_requests add constraint FK8llp5g8rr5yow78xeutr4xkmi foreign key (user_id) references users (id);
