-- ISO minor units: JPY 0, CHF 2, KWD 3, CLF 4. Input precision is validated per currency.
ALTER TABLE pms_cash_shifts MODIFY COLUMN opening_float DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_cash_shifts MODIFY COLUMN expected_cash DECIMAL(19,4) NULL;
ALTER TABLE pms_cash_shifts MODIFY COLUMN actual_cash DECIMAL(19,4) NULL;
ALTER TABLE pms_cash_shifts MODIFY COLUMN variance DECIMAL(19,4) NULL;
ALTER TABLE pms_folio_items MODIFY COLUMN unit_price DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_folio_items MODIFY COLUMN total_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_hotel_resources MODIFY COLUMN hourly_rate DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_migration_batches MODIFY COLUMN total_opening_balance DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_night_audits MODIFY COLUMN open_balance DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_payments MODIFY COLUMN amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_credit_accounts MODIFY COLUMN credit_limit DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_event_order_lines MODIFY COLUMN net_unit_price DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_event_order_lines MODIFY COLUMN net_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_event_order_lines MODIFY COLUMN tax_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_event_order_lines MODIFY COLUMN gross_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_invoices MODIFY COLUMN net_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_invoices MODIFY COLUMN vat_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_invoices MODIFY COLUMN gross_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_invoice_lines MODIFY COLUMN net_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_invoice_lines MODIFY COLUMN vat_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_invoice_lines MODIFY COLUMN gross_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_payment_requests MODIFY COLUMN amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_payment_requests MODIFY COLUMN capture_amount DECIMAL(19,4) NULL;
ALTER TABLE pms_receivables MODIFY COLUMN amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_receivables MODIFY COLUMN settled_amount DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_receivables MODIFY COLUMN credited_amount DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_receivable_settlements MODIFY COLUMN amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_pos_tickets MODIFY COLUMN net_amount DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_pos_tickets MODIFY COLUMN tax_amount DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_pos_tickets MODIFY COLUMN gross_amount DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_pos_ticket_lines MODIFY COLUMN unit_price DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_pos_ticket_lines MODIFY COLUMN net_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_pos_ticket_lines MODIFY COLUMN tax_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_pos_ticket_lines MODIFY COLUMN gross_amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_rate_overrides MODIFY COLUMN price DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_rate_plans MODIFY COLUMN nightly_rate DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_rate_plans MODIFY COLUMN breakfast_amount DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_rate_plans MODIFY COLUMN extra_adult_rate DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_rate_plans MODIFY COLUMN child_rate DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_reservations MODIFY COLUMN total_amount DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_resource_bookings MODIFY COLUMN total_amount DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_tourism_tax_postings MODIFY COLUMN amount DECIMAL(19,4) NOT NULL;
ALTER TABLE pms_tourism_tax_rules MODIFY COLUMN adult_rate DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_tourism_tax_rules MODIFY COLUMN child_rate DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE pms_invoices MODIFY COLUMN vat_rate DECIMAL(7,4) NOT NULL;
