import { useCallback, useEffect, useRef, useState } from 'react';
import api from '../../utils/api.js';
import usePmsLiveRefresh from './usePmsLiveRefresh.js';

const initialPeriod = (timezone = 'UTC') => {
    const parts = new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date());
    const part = (key) => parts.find((p) => p.type === key)?.value;
    const from = `${part('year')}-${part('month')}-${part('day')}`;
    const end = new Date(`${from}T12:00:00Z`); end.setUTCDate(end.getUTCDate() + 30);
    return { from, to: end.toISOString().slice(0, 10) };
};
const labels = { PENDING: 'Eingeplant', PROCESSING: 'Wird übertragen', COMPLETE: 'Bestätigt', FAILED: 'Prüfung erforderlich', CANCELLED: 'Verworfen' };
export default function PmsBeds24Panel({ property, canManage, canManageSettings }) {
    const [data, setData] = useState(null); const [draft, setDraft] = useState(null); const [dirty, setDirty] = useState(false);
    const [period, setPeriod] = useState(() => initialPeriod(property.timezone));
    const [intent, setIntent] = useState(null); const [reconciliation, setReconciliation] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
    const [links, setLinks] = useState({});
    const scope = useRef(property.id); scope.current = property.id;
    const load = useCallback(async (replaceDraft = false) => { const { data: next } = await api.get(`/api/pms/properties/${property.id}/beds24`); if (scope.current !== property.id) return; if (!Array.isArray(next?.mappings) || !Array.isArray(next?.jobs)) throw new Error('Ungültige Anbieterübersicht'); setData(next); if (replaceDraft) { setDraft(next); setDirty(false); } }, [property.id]);
    useEffect(() => { let active = true; load(true).catch(() => { if (active) setError('Beds24 konnte nicht geladen werden.'); }); return () => { active = false; }; }, [load]);
    const refresh = useCallback(() => load(false), [load]); usePmsLiveRefresh(refresh, { enabled: !busy });
    const change = (values) => { setDraft((value) => ({ ...value, ...values })); setDirty(true); setNotice(''); };
    const perform = async (callback, message) => { if (busy) return false; const started = property.id; setBusy(true); setError(''); setNotice(''); try { await callback(); if (scope.current !== started) return false; await load(); setNotice(message); return true; } catch (err) { if (scope.current === started) setError(err.response?.data?.detail || 'Anbieterauftrag konnte nicht bestätigt werden.'); return false; } finally { if (scope.current === started) setBusy(false); } };
    const save = (event) => { event.preventDefault(); if (!canManageSettings) return; perform(async () => { const { data: saved } = await api.put(`/api/pms/properties/${property.id}/beds24/settings`, { externalPropertyId: Number(draft.externalPropertyId), secretReference: draft.secretReference, enabled: draft.enabled, mappings: draft.mappings.map((m) => ({ ratePlanId: Number(m.ratePlanId), externalRoomId: Number(m.externalRoomId), priceSlot: Number(m.priceSlot) })), version: draft.version }); if (scope.current === property.id) { setDraft(saved); setDirty(false); } }, 'Beds24-Zuordnung gespeichert.'); };
    const publish = (event) => { event.preventDefault(); if (!canManage) return; const payload = intent || { ...period, requestId: crypto.randomUUID() }; setIntent(payload); perform(async () => { try { await api.post(`/api/pms/properties/${property.id}/beds24/publications`, payload); } catch (err) { if ([400, 403, 404, 409, 422].includes(err.response?.status)) setIntent(null); throw err; } if (scope.current === property.id) setIntent(null); }, 'Kalenderstand gespeichert und zur Übertragung eingeplant.'); };
    const linkBooking = (event, booking) => { event.preventDefault(); if (!canManage) return; perform(async () => { const { data: linked } = await api.post(`/api/pms/properties/${property.id}/beds24/bookings/${booking.bookingId}/link`, { reservationId: Number(links[booking.bookingId]) }); if (scope.current === property.id) setReconciliation((rows) => rows?.map((row) => row.bookingId === booking.bookingId ? linked : row)); }, 'Buchung geprüft und mit der Chrono-Reservierung verknüpft.'); };
    return <section className="pms-work-card pms-enterprise-card">
        <div className="pms-work-card-heading"><div><span className="pms-eyebrow">Konkrete Anbieteranbindung</span><h3>Beds24 · Preise, Bestand & Buchungsabgleich</h3></div><span className="pms-status-pill">{data?.workerEnabled ? 'Übertragung aktiv' : 'Server-Übertragung inaktiv'}</span></div>
        {error && <div role="alert" className="pms-inline-message is-error">{error}</div>}{notice && <div role="status" className="pms-inline-message is-success">{notice}</div>}
        <p className="pms-muted">Zimmerkategorien werden genau einer Beds24-Zimmer-ID zugeordnet. Jeder Preisslot enthält den Bruttopreis für die in der Rate enthaltene Belegung. Übertragene Kalenderstände bleiben als wiederholbare Aufträge gespeichert.</p>
        {draft && <details className="pms-enterprise-details"><summary>Verbindung & Ratenzuordnung</summary><form className="pms-form-grid" onSubmit={save}>
            <label>Beds24-Hotel-ID<input type="number" min="1" required value={draft.externalPropertyId || ''} disabled={!canManageSettings || busy} onChange={(event) => change({ externalPropertyId: event.target.value })} /></label>
            <label>Server-Tokenreferenz<input required placeholder="env:BEDS24_HOTEL_TOKEN" value={draft.secretReference || ''} disabled={!canManageSettings || busy} onChange={(event) => change({ secretReference: event.target.value })} /></label>
            <label className="pms-check-row is-wide"><input type="checkbox" checked={Boolean(draft.enabled)} disabled={!canManageSettings || busy} onChange={(event) => change({ enabled: event.target.checked })} />Verbindung freigeben und Hotelzuordnung beim Anbieter prüfen</label>
            <div className="pms-table-scroll is-wide"><table className="pms-access-table"><thead><tr><th>Chrono-Rate</th><th>Beds24-Zimmer-ID</th><th>Preisslot</th><th>Aktion</th></tr></thead><tbody>{draft.mappings.map((mapping, index) => <tr key={index}><td><select aria-label={`Chrono-Rate ${index + 1}`} required value={mapping.ratePlanId || ''} disabled={!canManageSettings || busy} onChange={(event) => change({ mappings: draft.mappings.map((m, i) => i === index ? { ...m, ratePlanId: event.target.value } : m) })}><option value="">Rate auswählen</option>{data?.rates?.map((rate) => <option key={rate.id} value={rate.id}>{rate.roomType} · {rate.name} · {rate.includedAdults} Erwachsene</option>)}</select></td><td><input aria-label={`Beds24-Zimmer-ID ${index + 1}`} type="number" min="1" required value={mapping.externalRoomId || ''} disabled={!canManageSettings || busy} onChange={(event) => change({ mappings: draft.mappings.map((m, i) => i === index ? { ...m, externalRoomId: event.target.value } : m) })} /></td><td><select aria-label={`Preisslot ${index + 1}`} value={mapping.priceSlot || 1} disabled={!canManageSettings || busy} onChange={(event) => change({ mappings: draft.mappings.map((m, i) => i === index ? { ...m, priceSlot: event.target.value } : m) })}>{Array.from({ length: 16 }, (_, i) => <option key={i + 1} value={i + 1}>Preis {i + 1}</option>)}</select></td><td><button type="button" disabled={!canManageSettings || busy} onClick={() => change({ mappings: draft.mappings.filter((_, i) => i !== index) })}>Entfernen</button></td></tr>)}</tbody></table></div>
            {canManageSettings && <div className="pms-form-actions is-wide"><button type="button" disabled={busy} onClick={() => change({ mappings: [...draft.mappings, { ratePlanId: '', externalRoomId: '', priceSlot: 1 }] })}>Rate zuordnen</button><button type="button" disabled={busy} onClick={() => load(true).catch(() => setError('Zuordnung konnte nicht geladen werden.'))}>Gespeicherte Zuordnung laden</button><button type="submit" className="is-primary" disabled={busy || !dirty}>Zuordnung speichern</button></div>}
        </form></details>}
        <form className="pms-form-grid" onSubmit={publish}><label>Von<input type="date" value={period.from} disabled={busy || Boolean(intent)} required onChange={(event) => setPeriod({ ...period, from: event.target.value })} /></label><label>Bis exklusiv<input type="date" value={period.to} disabled={busy || Boolean(intent)} required onChange={(event) => setPeriod({ ...period, to: event.target.value })} /></label><div className="pms-form-actions is-wide"><button type="button" disabled={busy || !data?.enabled} onClick={() => perform(async () => { const { data: rows } = await api.get(`/api/pms/properties/${property.id}/beds24/reconciliation`, { params: period }); if (scope.current === property.id) setReconciliation(rows); }, 'Buchungsabgleich geladen.')}>Buchungen abgleichen</button><button type="submit" className="is-primary" disabled={busy || !canManage || !data?.enabled}>{intent ? 'Denselben Kalenderauftrag erneut prüfen' : 'Aktuellen Kalenderstand übertragen'}</button></div></form>
        <h4>Übertragungsjournal</h4><div className="pms-table-scroll"><table className="pms-access-table"><thead><tr><th>Zeitraum</th><th>Status</th><th>Versuche</th><th>Aktionen</th></tr></thead><tbody>{data?.jobs?.map((job) => <tr key={job.id}><td>{job.from} – {job.to}<small className="pms-table-subline">{job.requestId}</small></td><td>{labels[job.status] || job.status}{job.error && <small className="pms-table-subline">{job.error}</small>}</td><td>{job.attempts}</td><td>{['FAILED', 'PENDING'].includes(job.status) && <div className="pms-record-actions"><button type="button" disabled={busy || !canManage} onClick={() => perform(() => api.post(`/api/pms/properties/${property.id}/beds24/publications/${job.id}/retry`), 'Gleicher Auftrag erneut eingeplant.')}>Erneut prüfen</button><button type="button" disabled={busy || !canManage} onClick={() => perform(() => api.post(`/api/pms/properties/${property.id}/beds24/publications/${job.id}/discard`), 'Auftrag verworfen; neuer Kalenderstand kann eingeplant werden.')}>Verwerfen</button></div>}</td></tr>)}</tbody></table>{data?.jobs?.length === 0 && <p className="pms-muted">Noch keine Kalenderübertragung.</p>}</div>
        {Array.isArray(reconciliation) && <><h4>Buchungsabgleich</h4><div className="pms-table-scroll"><table className="pms-access-table"><thead><tr><th>Beds24-Buchung</th><th>Zeitraum</th><th>Anbieterstatus</th><th>Chrono-Abgleich</th></tr></thead><tbody>{reconciliation.map((booking) => <tr key={booking.bookingId}><td>{booking.bookingId} · Zimmer-ID {booking.roomId}</td><td>{booking.arrival} – {booking.departure}</td><td>{booking.status}</td><td>{booking.result === 'MATCHED' ? 'Stimmt überein' : booking.result === 'NOT_LINKED' ? 'Noch keine verknüpfte Chrono-Reservierung' : 'Abweichung prüfen'}{booking.reservationId && <small className="pms-table-subline">Reservierung {booking.reservationId}</small>}{booking.result === 'NOT_LINKED' && canManage && <form className="pms-record-actions" onSubmit={(event) => linkBooking(event, booking)}><label>Chrono-Reservierungs-ID<input aria-label={`Chrono-Reservierungs-ID für ${booking.bookingId}`} type="number" min="1" required disabled={busy} value={links[booking.bookingId] || ''} onChange={(event) => setLinks((values) => ({ ...values, [booking.bookingId]: event.target.value }))} /></label><button type="submit" disabled={busy}>Prüfen & verknüpfen</button></form>}</td></tr>)}</tbody></table></div><p className="pms-muted">Neue Buchungen und Abweichungen müssen im Reservierungsprozess übernommen bzw. korrigiert werden. Der Abgleich verändert keine akzeptierten Preise oder Gastkonten.</p></>}
    </section>;
}
