import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import api from '../../utils/api.js';
import { formatPmsMoney } from './pmsMoney.js';
import { formatPmsDateTime } from './pmsFormatting.js';
import './PmsCommercialPanels.css';
export default function PmsEventOfferPage(){
 const {token}=useParams(),[offer,setOffer]=useState(null),[name,setName]=useState(''),[note,setNote]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const base=`/api/public/pms/event-offers/${encodeURIComponent(token||'')}`;
 useEffect(()=>{const controller=new AbortController();api.get(base,{signal:controller.signal}).then(({data})=>setOffer(data)).catch(e=>{if(!controller.signal.aborted)setError(e?.response?.data?.detail||'Angebot konnte nicht geladen werden.');});return()=>controller.abort();},[base]);
 const decide=async decision=>{if(busy||!name.trim()||(decision==='ACCEPTED'&&!consent))return;setBusy(true);setError('');try{const {data}=await api.post(`${base}/decision`,{decision,signatureName:name.trim(),note,consent});setOffer(data);}catch(e){try{const {data}=await api.get(base);setOffer(data);if(data.status==='OPEN')setError(e?.response?.data?.detail||'Entscheidung noch nicht bestätigt. Bitte erneut versuchen.');}catch{setError('Entscheidung konnte nicht bestätigt werden. Bitte diesen Link erneut öffnen, bevor Sie einen neuen Vorgang beginnen.');}}finally{setBusy(false);}};
 return <main className="pms-public-offer"><header><span>CHRONO · VERANSTALTUNGSANGEBOT</span><h1>{offer?.order?.title||'Ihr Veranstaltungsangebot'}</h1></header>{error&&<p role="alert">{error}</p>}{offer&&<><section><div className="pms-commercial-actions"><strong>Version {offer.version}</strong><span>{offer.status==='OPEN'?'Zur Entscheidung':offer.status==='ACCEPTED'?'Angebot angenommen':offer.status==='DECLINED'?'Angebot abgelehnt':'Angebot nicht mehr offen'}</span></div><h2>{formatPmsMoney(offer.order.grossAmount,offer.order.currencyCode)}</h2><p>{offer.order.resourceName} · {offer.order.attendees} Personen</p><p>{formatPmsDateTime(offer.order.startAt)} – {formatPmsDateTime(offer.order.endAt)}</p><p>Gültig bis {formatPmsDateTime(offer.validUntil)} (Hotelzeit)</p><div className="pms-commercial-scroll"><table><thead><tr><th>Leistung</th><th>Menge</th><th>Netto/Einheit</th><th>Steuer</th><th>Brutto</th></tr></thead><tbody>{offer.order.lines.map(line=><tr key={line.id}><td>{line.description}</td><td>{line.quantity}</td><td>{formatPmsMoney(line.netUnitPrice,offer.order.currencyCode)}</td><td>{line.taxRate}%</td><td>{formatPmsMoney(line.grossAmount,offer.order.currencyCode)}</td></tr>)}</tbody></table></div><h3>Vereinbarungen</h3><p className="pms-commercial-pre">{offer.terms}</p><details><summary>Ablauf, Aufbau und Bewirtung</summary><p className="pms-commercial-pre">{[offer.order.agenda,offer.order.setupInstructions,offer.order.cateringNotes].filter(Boolean).join('\n\n')}</p></details></section>
 {offer.status==='OPEN'?<section><h2>Ihre Entscheidung</h2><label>Vollständiger Name<input value={name} maxLength="180" onChange={e=>setName(e.target.value)} required disabled={busy}/></label><label>Hinweis (optional)<textarea value={note} maxLength="1000" onChange={e=>setNote(e.target.value)} disabled={busy}/></label><label className="pms-checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={busy}/>Ich nehme diese Angebotsversion einschließlich der angezeigten Leistungen und Bedingungen an.</label><p>Ihre Entscheidung wird zusammen mit Name, Zeitpunkt und der Prüfsumme dieser Version protokolliert.</p><div className="pms-commercial-actions"><button type="button" disabled={busy||!name.trim()||!consent} onClick={()=>decide('ACCEPTED')}>Angebot verbindlich annehmen</button><button type="button" disabled={busy||!name.trim()} onClick={()=>decide('DECLINED')}>Angebot ablehnen</button></div></section>:<section><h2>Entscheidung dokumentiert</h2><p>{offer.signatureName} · {formatPmsDateTime(offer.decidedAt)}</p><p>Version {offer.version} · {offer.status==='ACCEPTED'?'Angenommen':offer.status==='DECLINED'?'Abgelehnt':'Nicht mehr zur Annahme verfügbar'}</p></section>}
 <footer>Inhaltsnachweis <code>{offer.contentHash}</code></footer></>}</main>;
}
