import { useEffect, useRef, useState } from 'react';
import api from '../../utils/api.js';
import { formatPmsMoney } from './pmsMoney.js';
import { formatPmsDateTime } from './pmsFormatting.js';
import './PmsCommercialPanels.css';
const statuses={OPEN:'Offen',ACCEPTED:'Angenommen',DECLINED:'Abgelehnt',SUPERSEDED:'Durch neuere Version ersetzt',EXPIRED:'Abgelaufen'};
export default function PmsEventOffersPanel({property,bookings=[],canManage=false,onChanged}) {
 const [bookingId,setBookingId]=useState(''),[offers,setOffers]=useState([]),[terms,setTerms]=useState(''),[validUntil,setValidUntil]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[link,setLink]=useState('');
 const scope=useRef('');scope.current=`${property.id}:${bookingId}`;const base=`/api/pms/properties/${property.id}/resource-bookings/${bookingId}/offers`;
 const load=async()=>{const current=scope.current;const {data}=await api.get(base);if(scope.current===current)setOffers(Array.isArray(data)?data:[]);};
 useEffect(()=>{let active=true;if(bookingId)load().catch(e=>{if(active)setError(e?.response?.data?.detail||'Angebote konnten nicht geladen werden.');});else setOffers([]);return()=>{active=false;};},[base]);
 const act=async operation=>{if(busy)return;const current=scope.current;setBusy(true);setError('');setNotice('');try{await operation();if(scope.current===current){await load();setNotice('Vorgang gespeichert.');}}catch(e){if(scope.current===current)setError(e?.response?.data?.detail||'Angebotsvorgang konnte nicht abgeschlossen werden.');}finally{if(scope.current===current)setBusy(false);}};
 return <section className="pms-work-card pms-enterprise-card pms-commercial-panel"><div className="pms-work-card-heading"><div><span className="pms-eyebrow">Verkauf & Kundenfreigabe</span><h3>Veranstaltungsangebote</h3><p className="pms-muted">Gespeicherte Leistungen als feste Angebotsversion anbieten und Kundenentscheidung dokumentieren.</p></div></div>
 {error&&<p role="alert" className="pms-inline-message is-error">{error}</p>}{notice&&<p role="status" className="pms-inline-message is-success">{notice}</p>}
 <label>Veranstaltung für das Angebot<select value={bookingId} disabled={busy||Boolean(terms||validUntil)} onChange={e=>{setBookingId(e.target.value);setLink('');}}><option value="">Veranstaltung wählen</option>{bookings.filter(b=>b.status!=='CANCELLED').map(b=><option key={b.id} value={b.id}>{b.title} · {formatPmsDateTime(b.startAt)}</option>)}</select></label>
 {bookingId&&<><form onSubmit={e=>{e.preventDefault();act(async()=>{await api.post(base,{terms,validUntil:validUntil.length===16?`${validUntil}:00`:validUntil});setTerms('');setValidUntil('');setLink('');});}}><fieldset disabled={!canManage||busy} className="pms-plain-fieldset"><div className="pms-form-grid"><label>Gültig bis (Hotelzeit)<input type="datetime-local" value={validUntil} onChange={e=>setValidUntil(e.target.value)} required/></label><label className="is-wide">Angebots- und Änderungsbedingungen<textarea rows="5" maxLength="16000" value={terms} onChange={e=>setTerms(e.target.value)} placeholder="Leistungsumfang, Zahlungsbedingungen und Bedingungen für Änderungen oder Absagen" required/></label></div><div className="pms-commercial-actions"><button className="is-primary" type="submit">Gespeicherten Auftrag als neue Version sichern</button><button type="button" onClick={()=>{setTerms('');setValidUntil('');}}>Entwurf verwerfen</button></div></fieldset></form>
 {link&&<div className="pms-commercial-link"><label>Kundenlink für diese Angebotsversion<input readOnly value={link} onFocus={e=>e.target.select()}/></label><p>Der Link wurde erstellt. Er wird nicht automatisch versendet. Ein neuer Link ersetzt den vorherigen.</p></div>}
 <div className="pms-commercial-offers">{offers.map(offer=><article key={offer.id}><div className="pms-work-card-heading"><strong>Version {offer.version}</strong><span className="pms-status-pill">{statuses[offer.status]||offer.status}</span></div><p>{formatPmsMoney(offer.order.grossAmount,offer.order.currencyCode)} · gültig bis {formatPmsDateTime(offer.validUntil)}</p><details><summary>Angebotsinhalt und Nachweis</summary><p className="pms-commercial-pre">{offer.terms}</p><ul>{offer.order.lines.map(line=><li key={line.id}>{line.quantity} × {line.description}: {formatPmsMoney(line.grossAmount,offer.order.currencyCode)}</li>)}</ul><p>Inhalt-Prüfsumme <code>{offer.contentHash}</code></p>{offer.decidedAt&&<p>Entscheidung von {offer.signatureName} am {formatPmsDateTime(offer.decidedAt)}.<br/>{offer.decisionNote}<br/>Nachweis <code>{offer.acceptanceHash}</code></p>}</details><div className="pms-commercial-actions">{offer.status==='OPEN'&&<button type="button" disabled={!canManage||busy} onClick={()=>act(async()=>{const {data}=await api.post(`${base}/${offer.id}/link`);setLink(`${window.location.origin}/pms-event-offer/${data.token}`);})}>Kundenlink erstellen</button>}{offer.status==='ACCEPTED'&&<button type="button" disabled={!canManage||busy||Boolean(offer.appliedAt)} onClick={()=>act(async()=>{await api.post(`${base}/${offer.id}/apply`);await onChanged?.();})}>{offer.appliedAt?'In Bankettauftrag übernommen':'Angenommene Version in Bankettauftrag übernehmen'}</button>}</div></article>)}</div></>}
 </section>;
}
