import { useEffect,useRef,useState } from 'react';
import api from '../../utils/api.js';
import { currencyStep } from './pmsMoney.js';
import './PmsCommercialPanels.css';
const fieldLabels={addressLine:'Straße und Hausnummer',postalCode:'Postleitzahl',city:'Ort',countryCode:'Wohnsitzland',nationalityCode:'Staatsangehörigkeit',documentNumber:'Ausweisnummer',vehiclePlate:'Fahrzeugkennzeichen',signatureName:'Bestätigender Name',privacyConsent:'Bestätigung der Angaben'};
export default function PmsInternationalPanel({property,isMaster=false,canManageFinance=false}) {
 const [settings,setSettings]=useState(null),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[matches,setMatches]=useState([]),[invoiceId,setInvoiceId]=useState(''),[check,setCheck]=useState(null),[zeroCategory,setZeroCategory]=useState(''),[zeroReason,setZeroReason]=useState(''),[prepaidAmount,setPrepaidAmount]=useState('');
 const scope=useRef(property.id);scope.current=property.id;const base=`/api/pms/properties/${property.id}`;const dirtyRef=useRef(dirty);dirtyRef.current=dirty;const initialized=useRef(null);
 useEffect(()=>{const controller=new AbortController();api.get(`${base}/international-settings`,{signal:controller.signal}).then(({data})=>{if(!controller.signal.aborted&&String(data?.propertyId)===String(property.id)){if(!dirtyRef.current)setSettings(data);if(initialized.current!==property.id){initialized.current=property.id;setZeroCategory(data.zeroTaxCategory||'');setZeroReason(data.zeroTaxReason||'');}}}).catch(e=>{if(!controller.signal.aborted)setError(e?.response?.data?.detail||'Konfiguration konnte nicht geladen werden.');});return()=>controller.abort();},[base,property.id]);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{api.get(`${base}/history/invoices`,{params:{query,page:0,size:20},signal:controller.signal}).then(({data})=>{if(!controller.signal.aborted)setMatches(Array.isArray(data?.items)?data.items:[]);}).catch(e=>{if(!controller.signal.aborted)setError(e?.response?.data?.detail||'Rechnungssuche fehlgeschlagen.');});},250);return()=>{clearTimeout(timer);controller.abort();};},[base,query]);
 const change=values=>{setSettings(current=>({...current,...values}));setDirty(true);};
 const act=async operation=>{if(busy)return;const id=property.id;setBusy(true);setError('');setNotice('');try{await operation();if(scope.current===id)setNotice('Vorgang abgeschlossen.');}catch(e){if(scope.current===id)setError(e?.response?.data?.detail||'Der Vorgang konnte nicht abgeschlossen werden.');}finally{if(scope.current===id)setBusy(false);}};
 const invoiceBase=`${base}/invoices/${invoiceId}`;
 return <section className="pms-work-card pms-enterprise-card pms-commercial-panel"><div className="pms-work-card-heading"><div><span className="pms-eyebrow">Land & strukturierte Dokumente</span><h3>Lokale Pflichtfelder und UBL-Rechnungen</h3><p className="pms-muted">Hotelbezogene Regeln mit Prüfquelle pflegen. Neue Gästeeinladungen behalten die bei ihrer Erstellung gültige Version.</p></div></div>
 {error&&<p role="alert" className="pms-inline-message is-error">{error}</p>}{notice&&<p role="status" className="pms-inline-message is-success">{notice}</p>}
 {settings&&<details open={isMaster&&!settings.configured}><summary>{settings.configured?`${settings.jurisdictionLabel} · Regelversion ${settings.version+1}`:'Lokale Regeln noch nicht konfiguriert'}</summary><form onSubmit={e=>{e.preventDefault();act(async()=>{const {data}=await api.put(`${base}/international-settings`,settings);setSettings(data);setDirty(false);});}}><fieldset disabled={!isMaster||busy} className="pms-plain-fieldset"><div className="pms-form-grid"><label>Regelcode<input maxLength="40" required pattern="[A-Z0-9-]{2,40}" value={settings.ruleCode} onChange={e=>change({ruleCode:e.target.value.toUpperCase()})}/></label><label>Land / Region / Rechtsraum<input maxLength="180" required value={settings.jurisdictionLabel} onChange={e=>change({jurisdictionLabel:e.target.value})}/></label><label className="is-wide">Fachliche Prüfquelle / Freigabereferenz<input maxLength="500" required value={settings.sourceReference} onChange={e=>change({sourceReference:e.target.value})}/></label>{settings.availableFields.map(field=><label key={field} className="pms-checkbox"><input type="checkbox" checked={settings.requiredFields.includes(field)} onChange={e=>change({requiredFields:e.target.checked?[...settings.requiredFields,field]:settings.requiredFields.filter(f=>f!==field)})}/>{fieldLabels[field]} verpflichtend</label>)}<label>Steuersystem im UBL-Dokument<select value={settings.taxScheme} onChange={e=>change({taxScheme:e.target.value})}><option value="VAT">VAT / Mehrwertsteuer</option><option value="GST">GST</option><option value="OTH">Andere Steuer</option></select></label><label>Standardkategorie für null Prozent<select value={settings.zeroTaxCategory||''} onChange={e=>change({zeroTaxCategory:e.target.value||null})}><option value="">Je Rechnung ausdrücklich festlegen</option><option value="Z">Z · Nullsatz</option><option value="E">E · Steuerbefreit</option><option value="AE">AE · Reverse Charge</option><option value="O">O · Außerhalb des Steuerbereichs</option></select></label><label className="is-wide">Begründung für Ausnahme / Reverse Charge<input maxLength="500" value={settings.zeroTaxReason||''} onChange={e=>change({zeroTaxReason:e.target.value||null})}/></label></div><p className="pms-muted">Die Konfiguration wird vom Hotel fachlich festgelegt. Die Länderkennung allein bestätigt keine lokalen Melde-, Steuer- oder Fiskalisierungsanforderungen.</p><button type="submit" className="is-primary" disabled={!dirty}>Lokale Regeln speichern</button></fieldset></form></details>}
 <h4>Strukturierte Rechnung aus gespeicherten Belegen</h4><div className="pms-form-grid"><label>Rechnungsnummer / Empfänger suchen<input maxLength="120" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Gesamtes Rechnungsjournal durchsuchen"/></label><label>Rechnung auswählen<select value={invoiceId} disabled={busy} onChange={e=>{setInvoiceId(e.target.value);setCheck(null);setPrepaidAmount('');}}><option value="">Rechnung wählen</option>{matches.map(invoice=><option key={invoice.id} value={invoice.id}>{invoice.invoiceNumber} · {invoice.recipientName}</option>)}</select></label><label>Dieser Rechnung zugeordnete Vorauszahlung<input type="number" min="0" step={currencyStep(property.currencyCode)} value={prepaidAmount} disabled={busy||check?.stored} onChange={e=>setPrepaidAmount(e.target.value)} placeholder="Betrag ausdrücklich angeben, auch 0"/></label><label>Nullsteuer-Kategorie dieser Rechnung<select value={zeroCategory} disabled={busy||check?.stored} onChange={e=>setZeroCategory(e.target.value)}><option value="">Hotelstandard / keine Nullsteuer</option><option value="Z">Z · Nullsatz</option><option value="E">E · Steuerbefreit</option><option value="AE">AE · Reverse Charge</option><option value="O">O · Außerhalb des Steuerbereichs</option></select></label><label>Begründung dieser Rechnung<input value={zeroReason} maxLength="500" disabled={busy||check?.stored} onChange={e=>setZeroReason(e.target.value)}/></label></div><div className="pms-commercial-actions"><button type="button" disabled={!invoiceId||busy} onClick={()=>act(async()=>{const {data}=await api.get(`${invoiceBase}/structured-invoice`);setCheck(data);})}>Gespeicherte Rechnung prüfen</button><button type="button" disabled={!invoiceId||busy||!canManageFinance||(!check?.stored&&prepaidAmount==='')} onClick={()=>act(async()=>{const {data}=await api.post(`${invoiceBase}/structured-invoice`,{zeroTaxCategory:zeroCategory||null,zeroTaxReason:zeroReason||null,prepaidAmount:prepaidAmount===''?null:Number(prepaidAmount)});setCheck(data);})}>UBL-Datei validieren und fest speichern</button><button type="button" disabled={!check?.stored||busy} onClick={()=>act(async()=>{const {data}=await api.get(`${invoiceBase}/ubl.xml`,{responseType:'blob'});const url=URL.createObjectURL(data);const a=document.createElement('a');a.href=url;a.download=`${check.invoiceNumber}.xml`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>Gespeicherte XML herunterladen</button></div>
 {check&&<div className="pms-commercial-rule"><strong>{check.ready?'Prüfung bestanden':'Prüfung enthält offene Punkte'}{check.stored?' · Datei unveränderlich gespeichert':''}</strong><p>{check.scope}</p>{check.errors.length>0&&<ul>{check.errors.map((text,index)=><li key={index}>{text}</li>)}</ul>}{check.contentHash&&<p>SHA-256 <code>{check.contentHash}</code></p>}</div>}<p className="pms-muted">Validierung gegen die offiziellen OASIS-UBL-2.1-Schemata sowie Pflichtfelder und Rechnungssummen. Peppol-Übertragung und nationale Zusatzprüfungen sind eigene Adapterprozesse.</p>
 </section>;
}
