import { useEffect, useRef, useState } from 'react';
import api from '../../utils/api.js';
import { currencyStep, formatPmsMoney } from './pmsMoney.js';
import { formatPmsDateTime } from './pmsFormatting.js';
import './PmsCommercialPanels.css';
const blank={sourceRatePlanId:'',targetRatePlanId:'',expectedVersion:null,enabled:false,frozen:false,inheritPolicy:false,manualFxRate:'1',fxDate:'',fxValidUntil:'',fxReference:'',adjustmentPercent:0,minPrice:'',maxPrice:''};
export default function PmsRateInheritancePanel({property,rates=[],canManage=false,isMaster=false}) {
 const [rules,setRules]=useState([]),[hotels,setHotels]=useState([]),[sourceHotel,setSourceHotel]=useState(''),[sourceRates,setSourceRates]=useState([]),[draft,setDraft]=useState(blank),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const scope=useRef(property.id);scope.current=property.id;const base=`/api/pms/properties/${property.id}/rate-inheritance`;
 const load=async()=>{const {data}=await api.get(base);if(Array.isArray(data))setRules(data);};
 useEffect(()=>{const controller=new AbortController();api.get(base,{signal:controller.signal}).then(({data})=>setRules(Array.isArray(data)?data:[])).catch(e=>{if(!controller.signal.aborted)setError(e?.response?.data?.detail||'Vererbungsregeln konnten nicht geladen werden.');});if(isMaster)api.get('/api/pms/setup',{params:{includeRooms:false},signal:controller.signal}).then(({data})=>setHotels(data.properties||[])).catch(()=>{});return()=>controller.abort();},[base,isMaster]);
 useEffect(()=>{if(!sourceHotel){setSourceRates([]);return;}const controller=new AbortController();api.get('/api/pms/operations',{params:{propertyId:Number(sourceHotel)},signal:controller.signal}).then(({data})=>setSourceRates(data.ratePlans||[])).catch(e=>{if(!controller.signal.aborted)setError(e?.response?.data?.detail||'Elternraten konnten nicht geladen werden.');});return()=>controller.abort();},[sourceHotel]);
 const change=values=>{setDraft(current=>({...current,...values}));setDirty(true);};
 const act=async operation=>{if(busy)return;const expected=property.id;setBusy(true);setError('');setNotice('');try{await operation();if(scope.current===expected){await load();setNotice('Ratenregel aktualisiert.');}}catch(e){if(scope.current===expected)setError(e?.response?.data?.detail||'Ratenregel konnte nicht aktualisiert werden.');}finally{if(scope.current===expected)setBusy(false);}};
 const edit=rule=>{setDraft({sourceRatePlanId:rule.sourceRatePlanId,targetRatePlanId:rule.targetRatePlanId,expectedVersion:rule.version,enabled:rule.enabled,frozen:rule.frozen,inheritPolicy:rule.inheritPolicy,manualFxRate:rule.manualFxRate,fxDate:rule.fxDate,fxValidUntil:rule.fxValidUntil,fxReference:rule.fxReference,adjustmentPercent:rule.adjustmentPercent,minPrice:rule.minPrice,maxPrice:rule.maxPrice});setDirty(true);setSourceHotel('');};
 return <section className="pms-work-card pms-enterprise-card pms-commercial-panel"><div className="pms-work-card-heading"><div><span className="pms-eyebrow">Zentrale Preisstruktur</span><h3>Elternraten und lokale Ausnahmen</h3><p className="pms-muted">Preise und optional Bedingungen aus einer festgelegten Elternrate übernehmen. Lokale Steuersätze bleiben erhalten.</p></div></div>
 {error&&<p role="alert" className="pms-inline-message is-error">{error}</p>}{notice&&<p role="status" className="pms-inline-message is-success">{notice}</p>}
 <div className="pms-commercial-offers">{rules.map(rule=><article key={rule.id}><div className="pms-work-card-heading"><strong>{rule.targetRateName}</strong><span className="pms-status-pill">{rule.frozen?'Lokale Ausnahme':rule.enabled?'Automatische Vererbung':'Manuelle Anwendung'}</span></div><p>{rule.sourceHotel} / {rule.sourceRateName} → {property.name}</p><p>Vorschau {formatPmsMoney(rule.previewPrice,rule.targetCurrency)} · {rule.adjustmentPercent}% Anpassung</p><p>{rule.sourceCurrency} → {rule.targetCurrency}: Kurs {rule.manualFxRate} · {rule.fxReference}</p><small>{rule.lastResult||'Noch nicht angewendet'}{rule.lastAppliedAt&&` · ${formatPmsDateTime(rule.lastAppliedAt)}`}</small><div className="pms-commercial-actions"><button type="button" disabled={!canManage||busy||dirty} onClick={()=>act(()=>api.patch(`${base}/${rule.id}/freeze`,{frozen:!rule.frozen,expectedVersion:rule.version}))}>{rule.frozen?'Vererbung wieder freigeben':'Als lokale Ausnahme einfrieren'}</button>{isMaster&&<><button type="button" disabled={busy||dirty||rule.frozen} onClick={()=>act(()=>api.post(`${base}/${rule.id}/apply`))}>Jetzt übernehmen</button><button type="button" disabled={busy||dirty} onClick={()=>edit(rule)}>Regel bearbeiten</button></>}</div></article>)}</div>
 {isMaster&&<form onSubmit={e=>{e.preventDefault();act(async()=>{await api.put(base,{...draft,sourceRatePlanId:Number(draft.sourceRatePlanId),targetRatePlanId:Number(draft.targetRatePlanId),manualFxRate:Number(draft.manualFxRate),adjustmentPercent:Number(draft.adjustmentPercent),minPrice:Number(draft.minPrice),maxPrice:Number(draft.maxPrice)});setDraft(blank);setDirty(false);setSourceHotel('');});}}><fieldset disabled={busy} className="pms-plain-fieldset"><h4>{draft.expectedVersion==null?'Neue Vererbungsregel':'Vererbungsregel bearbeiten'}</h4><div className="pms-form-grid">
 <label>Hotel der Elternrate<select value={sourceHotel} onChange={e=>{setSourceHotel(e.target.value);change({sourceRatePlanId:''});}}><option value="">Hotel wählen</option>{hotels.map(h=><option key={h.id} value={h.id}>{h.name} · {h.currencyCode}</option>)}</select></label><label>Elternrate<select required value={draft.sourceRatePlanId} onChange={e=>change({sourceRatePlanId:e.target.value})}><option value="">Elternrate wählen</option>{draft.sourceRatePlanId&&!sourceRates.some(r=>String(r.id)===String(draft.sourceRatePlanId))&&<option value={draft.sourceRatePlanId}>Gespeicherte Elternrate #{draft.sourceRatePlanId}</option>}{sourceRates.map(r=><option key={r.id} value={r.id}>{r.name} · {r.currencyCode}</option>)}</select></label>
 <label>Lokale Zielrate<select required value={draft.targetRatePlanId} disabled={draft.expectedVersion!=null} onChange={e=>{const rate=rates.find(r=>String(r.id)===e.target.value);change({targetRatePlanId:e.target.value,minPrice:rate?.nightlyRate??'',maxPrice:rate?.nightlyRate??''});}}><option value="">Zielrate wählen</option>{rates.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 <label>Manueller Kurs (Zielwährung je 1 Elternwährung)<input type="number" min="0.00000001" step="0.00000001" required value={draft.manualFxRate} onChange={e=>change({manualFxRate:e.target.value})}/></label><label>Kursdatum<input type="date" required value={draft.fxDate} onChange={e=>change({fxDate:e.target.value})}/></label><label>Kurs gültig bis<input type="date" required value={draft.fxValidUntil} onChange={e=>change({fxValidUntil:e.target.value})}/></label><label className="is-wide">Kursquelle / Freigabereferenz<input required maxLength="240" value={draft.fxReference} onChange={e=>change({fxReference:e.target.value})} placeholder="z. B. intern freigegebener Monatskurs; bei gleicher Währung Kurs 1"/></label>
 {[['adjustmentPercent','Anpassung zur Elternrate (%)',-90,200,.01],['minPrice',`Mindestpreis (${property.currencyCode})`,0,null,currencyStep(property.currencyCode)],['maxPrice',`Höchstpreis (${property.currencyCode})`,0,null,currencyStep(property.currencyCode)]].map(([key,label,min,max,step])=><label key={key}>{label}<input type="number" required min={min} max={max} step={step} value={draft[key]} onChange={e=>change({[key]:e.target.value})}/></label>)}
 {[['enabled','Änderungen der Elternrate automatisch übernehmen'],['frozen','Lokale Ausnahme: Vererbung eingefroren'],['inheritPolicy','Aufenthalts-, Anzahlungs- und Stornobedingungen mit übernehmen']].map(([key,label])=><label key={key} className="pms-checkbox"><input type="checkbox" checked={draft[key]} onChange={e=>change({[key]:e.target.checked})}/>{label}</label>)}</div><p className="pms-muted">Manuelle Änderungen der Zielrate frieren deren Vererbung ein. Abgelaufene Fremdwährungskurse sperren neue Übernahmen; gespeicherte Reservierungsbedingungen werden nicht verändert.</p><div className="pms-commercial-actions"><button type="submit" className="is-primary" disabled={!dirty}>Vererbungsregel speichern</button><button type="button" onClick={()=>{setDraft(blank);setDirty(false);setSourceHotel('');}}>Entwurf verwerfen</button></div></fieldset></form>}
 </section>;
}
