import { useEffect, useRef, useState } from 'react';
import api from '../../utils/api.js';
import { currencyStep, formatPmsMoney } from './pmsMoney.js';
import { formatPmsDate } from './pmsFormatting.js';
import './PmsCommercialPanels.css';
const errorText = e => e?.response?.data?.detail || 'Die Revenue-Daten konnten nicht verarbeitet werden.';
export default function PmsRevenueAutomationPanel({ property, rates = [], canManageRates = false, isMaster = false }) {
 const [config,setConfig]=useState(null),[forecast,setForecast]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[rateId,setRateId]=useState('');
 const generation=useRef(0),scope=useRef(property.id);scope.current=property.id;
 const base=`/api/pms/properties/${property.id}/reports/revenue-planning`;
 useEffect(()=>{const id=++generation.current,controller=new AbortController();Promise.all([api.get(`${base}/automation`,{signal:controller.signal}),api.get(`${base}/forecast`,{signal:controller.signal,params:{days:30}})]).then(([c,f])=>{if(generation.current===id&&!controller.signal.aborted){if(!c.data||String(c.data.propertyId)!==String(property.id)||!Array.isArray(c.data.rules)||!Array.isArray(f.data?.days))throw Error();setConfig(c.data);setForecast(f.data);}}).catch(e=>{if(!controller.signal.aborted)setError(errorText(e));});return()=>controller.abort();},[base,property.id]);
 const change=values=>{setConfig(current=>({...current,...values}));setDirty(true);};
 const act=async action=>{if(busy)return;const id=property.id;setBusy(true);setError('');setNotice('');try{await action();if(scope.current===id)setNotice('Änderung gespeichert.');}catch(e){if(scope.current===id)setError(errorText(e));}finally{if(scope.current===id)setBusy(false);}};
 const reload=async()=>{const {data}=await api.get(`${base}/forecast`,{params:{days:config?.horizonDays||30}});if(String(data?.propertyId)===String(scope.current))setForecast(data);};
 return <section className="pms-work-card pms-enterprise-card pms-commercial-panel">
  <div className="pms-work-card-heading"><div><span className="pms-eyebrow">Nachfrage & Preise</span><h3>Prognose und begrenzte Automatik</h3><p className="pms-muted">Vergleichbare abgeschlossene Tage und tatsächlicher Buchungszuwachs bilden die Grundlage.</p></div><button type="button" disabled={busy} onClick={()=>act(reload)}>Neu berechnen</button></div>
  {error&&<p role="alert" className="pms-inline-message is-error">{error}</p>}{notice&&<p role="status" className="pms-inline-message is-success">{notice}</p>}
  {forecast&&<><div className="pms-day-checks"><div><span>Beobachtete abgeschlossene Tage</span><strong>{forecast.observedDays}</strong></div><div><span>Aktuell betriebsbereite Zimmer</span><strong>{forecast.capacity}</strong></div><div><span>Tage mit ausreichender Grundlage</span><strong>{forecast.days.filter(day=>day.expectedRoomNights!=null).length} / {forecast.days.length}</strong></div></div><p className="pms-muted">{forecast.model}</p>
   <div className="pms-commercial-scroll"><table><thead><tr><th>Datum</th><th>Gebucht</th><th>Prognose</th><th>Beobachtete Spanne</th><th>Nettoerlös</th><th>Vergleichstage / Saison / Pickup</th></tr></thead><tbody>{forecast.days.map(day=><tr key={day.date}><td>{formatPmsDate(day.date)}</td><td>{day.onBooks}</td><td>{day.expectedRoomNights??'Daten fehlen'}</td><td>{day.lowerRoomNights==null?'—':`${day.lowerRoomNights}–${day.upperRoomNights}`}</td><td>{day.expectedNetRoomRevenue==null?'—':formatPmsMoney(day.expectedNetRoomRevenue,property.currencyCode)}</td><td>{day.samples} / {day.seasonalSamples} / {day.pickupSamples}</td></tr>)}</tbody></table></div>
   {forecast.suggestions.length>0&&<details><summary>{forecast.suggestions.length} regelbasierte Preisvorschläge</summary><div className="pms-commercial-scroll"><table><thead><tr><th>Rate / Datum</th><th>Aktuell</th><th>Vorschlag</th><th>Grundlage</th><th>Aktion</th></tr></thead><tbody>{forecast.suggestions.map(s=><tr key={`${s.ratePlanId}:${s.stayDate}`}><td>{s.rateName}<br/>{formatPmsDate(s.stayDate)}</td><td>{formatPmsMoney(s.currentPrice,property.currencyCode)}</td><td>{formatPmsMoney(s.proposedPrice,property.currencyCode)}</td><td>{s.reason}</td><td><button type="button" disabled={!canManageRates||busy||dirty||Number(s.currentPrice)===Number(s.proposedPrice)} onClick={()=>act(async()=>{await api.post(`${base}/pricing/apply`,{ratePlanId:s.ratePlanId,stayDate:s.stayDate,expectedCurrentPrice:s.currentPrice,proposedPrice:s.proposedPrice});await reload();})}>Diesen Preis übernehmen</button></td></tr>)}</tbody></table></div></details>}
  </>}
  {config&&<form onSubmit={event=>{event.preventDefault();act(async()=>{const {data}=await api.put(`${base}/automation`,config);setConfig(data);setDirty(false);await reload();});}}><fieldset disabled={!canManageRates||busy} className="pms-plain-fieldset"><h4>Regeln und Schutzgrenzen</h4><div className="pms-form-grid">
   <label className="pms-checkbox"><input type="checkbox" checked={config.snapshotsEnabled} onChange={e=>change({snapshotsEnabled:e.target.checked})}/>Täglichen Vergleichsstand automatisch speichern</label>
   <label className="pms-checkbox"><input type="checkbox" checked={config.pricingEnabled} disabled={!isMaster} onChange={e=>change({pricingEnabled:e.target.checked})}/>Preisautomatik aktivieren (Master)</label>
   <label>Horizont (Tage)<input type="number" min="1" max="90" value={config.horizonDays} onChange={e=>change({horizonDays:Number(e.target.value)})} required/></label><label>Mindestzahl vergleichbarer Tage<input type="number" min="4" max="52" value={config.minSamples} onChange={e=>change({minSamples:Number(e.target.value)})} required/></label>
  </div><p className="pms-muted">Automatik läuft höchstens einmal je Betriebstag, verändert keine vorhandenen Reservierungen und überspringt manuelle Tagespreise. Ohne ausreichend Vergleichsdaten gibt es keine automatische Änderung.</p>
  {config.rules.map((rule,index)=><article key={rule.ratePlanId} className="pms-commercial-rule"><strong>{rates.find(rate=>rate.id===rule.ratePlanId)?.name||`Rate ${rule.ratePlanId}`}</strong><div className="pms-form-grid">{[['minPrice','Mindestpreis',0,null,currencyStep(property.currencyCode)],['maxPrice','Höchstpreis',0,null,currencyStep(property.currencyCode)],['maxChangePercent','Max. Änderung je Lauf (%)',0,25,.01],['adjustmentPercent','Zu-/Abschlag zur Basis (%)',0,25,.01],['lowOccupancy','Untere Belegungsschwelle (%)',0,99,1],['highOccupancy','Obere Belegungsschwelle (%)',1,100,1]].map(([key,label,min,max,step])=><label key={key}>{label}<input type="number" min={min} max={max} step={step} value={rule[key]} required onChange={e=>change({rules:config.rules.map((item,i)=>i===index?{...item,[key]:Number(e.target.value)}:item)})}/></label>)}</div><button type="button" onClick={()=>change({rules:config.rules.filter((_,i)=>i!==index)})}>Regel entfernen</button></article>)}
  <div className="pms-commercial-actions"><label>Rate ergänzen<select value={rateId} onChange={e=>setRateId(e.target.value)}><option value="">Rate auswählen</option>{rates.filter(rate=>!config.rules.some(rule=>rule.ratePlanId===rate.id)).map(rate=><option key={rate.id} value={rate.id}>{rate.name}</option>)}</select></label><button type="button" disabled={!rateId} onClick={()=>{const rate=rates.find(item=>String(item.id)===rateId);change({rules:[...config.rules,{ratePlanId:rate.id,minPrice:Number(rate.nightlyRate),maxPrice:Number(rate.nightlyRate),maxChangePercent:5,adjustmentPercent:5,lowOccupancy:40,highOccupancy:80}]});setRateId('');}}>Preisregel ergänzen</button><button type="submit" className="is-primary" disabled={!dirty}>Regeln speichern</button></div></fieldset></form>}
 </section>;
}
