server {
  listen 80;
  server_name www.chrono-logisch.ch;

  return 301 https://chrono-logisch.ch$request_uri;
}

server {
  listen 80 default_server;
  server_name chrono-logisch.ch _;

  # React-SPA
  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    try_files $uri /index.html;
  }

  # Block PHP / WP-Scanner
  location ~* \.php$ {
    return 404;
  }

  location = /wlwmanifest.xml {
    return 404;
  }

  error_page 404 /index.html;
}
