package com.chrono.chrono.services.pms;
import com.chrono.chrono.dto.pms.CompleteGuestRegistrationRequest;
import com.chrono.chrono.entities.pms.*;
import com.chrono.chrono.repositories.pms.HotelPropertyRepository;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.persistence.EntityManager;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class PmsInternationalSettingsService {
 public static final List<String> FIELDS=List.of("addressLine","postalCode","city","countryCode","nationalityCode","documentNumber","vehiclePlate","signatureName","privacyConsent");
 public static final List<String> LEGACY_FIELDS=FIELDS.stream().filter(f->!f.equals("vehiclePlate")).toList();
 public record Settings(Long propertyId,long version,String countryCode,String ruleCode,String jurisdictionLabel,String sourceReference,List<String> requiredFields,List<String> availableFields,String taxScheme,String zeroTaxCategory,String zeroTaxReason,boolean configured) {}
 private final EntityManager em;private final HotelPropertyRepository properties;private final PmsPropertyAccessService access;private final PmsAuditWriter audit;private final ObjectMapper json;
 @Transactional(readOnly=true) public Settings get(String user,Long id){var actor=access.access(user);access.require(actor,id,"FINANCE",false);HotelProperty hotel=properties.findByIdAndCompany_Id(id,actor.companyId()).orElseThrow(()->bad("Hotel nicht gefunden."));return settings(hotel);}
 public Settings save(String user,Long id,Settings input){var actor=access.requireMaster(user);HotelProperty hotel=properties.findByIdAndCompany_IdForUpdate(id,actor.companyId()).orElseThrow(()->bad("Hotel nicht gefunden."));if(input==null||input.requiredFields()==null||input.requiredFields().size()>FIELDS.size()||!FIELDS.containsAll(input.requiredFields())||new HashSet<>(input.requiredFields()).size()!=input.requiredFields().size()||input.ruleCode()==null||!input.ruleCode().matches("[A-Z0-9-]{2,40}")||input.jurisdictionLabel()==null||input.jurisdictionLabel().isBlank()||input.jurisdictionLabel().length()>180||input.sourceReference()==null||input.sourceReference().isBlank()||input.sourceReference().length()>500||!Set.of("VAT","GST","OTH").contains(input.taxScheme()))throw bad("Regelcode, Rechtsraum, Prüfquelle und gültige Pflichtfelder angeben.");
  String category=clean(input.zeroTaxCategory()),reason=clean(input.zeroTaxReason());if(category!=null&&!Set.of("Z","E","AE","O").contains(category)||category!=null&&!category.equals("Z")&&(reason==null||reason.length()>500))throw bad("Nullsteuer-Kategorie Z, E, AE oder O wählen; Ausnahmen benötigen einen Grund.");
  PmsInternationalSettings row=em.find(PmsInternationalSettings.class,id);if(row!=null&&row.getVersion()!=input.version())throw new ResponseStatusException(HttpStatus.CONFLICT,"Die internationale Konfiguration wurde inzwischen geändert.");if(row==null){row=new PmsInternationalSettings();row.setPropertyId(id);em.persist(row);}row.setRuleCode(input.ruleCode());row.setJurisdictionLabel(input.jurisdictionLabel().trim());row.setSourceReference(input.sourceReference().trim());row.setRequiredFieldsJson(encode(input.requiredFields()));row.setTaxScheme(input.taxScheme());row.setZeroTaxCategory(category);row.setZeroTaxReason(reason);em.flush();audit.append(hotel,"international.settings_changed","property",id.toString(),"{\"ruleCode\":\""+row.getRuleCode()+"\",\"version\":"+row.getVersion()+"}");return settings(hotel);}
 @Transactional(readOnly=true) public Settings settings(HotelProperty hotel){PmsInternationalSettings row=em.find(PmsInternationalSettings.class,hotel.getId());if(row==null)return new Settings(hotel.getId(),0,hotel.getCountryCode(),hotel.getCountryCode()+"-REGISTRATION",hotel.getCountryCode(),"Noch keine lokale fachliche Konfiguration",LEGACY_FIELDS,FIELDS,"VAT",null,null,false);return new Settings(hotel.getId(),row.getVersion(),hotel.getCountryCode(),row.getRuleCode(),row.getJurisdictionLabel(),row.getSourceReference(),decode(row.getRequiredFieldsJson()),FIELDS,row.getTaxScheme(),row.getZeroTaxCategory(),row.getZeroTaxReason(),true);}
 public void snapshot(GuestRegistration registration){Settings settings=settings(registration.getReservation().getProperty());if(!settings.configured())return;registration.setRuleCode(settings.ruleCode());registration.setRuleVersion(Math.toIntExact(settings.version()+1));registration.setRequiredFieldsSnapshot(encode(settings.requiredFields()));}
 public List<String> requiredFields(GuestRegistration registration){return registration.getRequiredFieldsSnapshot()==null?LEGACY_FIELDS:decode(registration.getRequiredFieldsSnapshot());}
 public void validate(GuestRegistration registration,CompleteGuestRegistrationRequest request){if(request==null)throw bad("Anmeldungsdaten fehlen.");for(String field:requiredFields(registration)){boolean present=switch(field){case "privacyConsent"->request.privacyConsent();case "addressLine"->present(request.addressLine());case "postalCode"->present(request.postalCode());case "city"->present(request.city());case "countryCode"->present(request.countryCode());case "nationalityCode"->present(request.nationalityCode());case "documentNumber"->present(request.documentNumber());case "vehiclePlate"->present(request.vehiclePlate());case "signatureName"->present(request.signatureName());default->false;};if(!present)throw bad("Pflichtfeld für "+registration.getRuleCode()+" fehlt: "+field);}
  for(String code:new String[]{request.countryCode(),request.nationalityCode()})if(present(code)&&!Set.of(Locale.getISOCountries()).contains(code.trim().toUpperCase(Locale.ROOT)))throw bad("Ungültiger ISO-Ländercode.");if(present(request.documentNumber())&&request.documentNumber().trim().length()<4)throw bad("Ausweisnummer muss mindestens vier Zeichen enthalten.");}
 private boolean present(String text){return text!=null&&!text.isBlank();}private String clean(String text){return present(text)?text.trim():null;}
 private String encode(List<String> fields){try{return json.writeValueAsString(fields);}catch(Exception failure){throw new IllegalStateException(failure);}}
 private List<String> decode(String value){try{return json.readValue(value,new TypeReference<List<String>>(){});}catch(Exception failure){throw new IllegalStateException("Ungültiger Pflichtfeld-Snapshot",failure);}}
 private ResponseStatusException bad(String text){return new ResponseStatusException(HttpStatus.BAD_REQUEST,text);}
}
