package com.chrono.chrono.services.pms;
import com.chrono.chrono.dto.pms.BillingProfile;
import com.chrono.chrono.entities.pms.*;
import com.chrono.chrono.repositories.pms.*;
import jakarta.persistence.EntityManager;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import org.w3c.dom.*;
import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.*;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import java.io.*;
import java.math.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.time.*;
import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class PmsStructuredInvoiceService {
 private static final String CBC="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2",CAC="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2";
 public record Options(String zeroTaxCategory,String zeroTaxReason,BigDecimal prepaidAmount) {
  public Options(String zeroTaxCategory,String zeroTaxReason){this(zeroTaxCategory,zeroTaxReason,BigDecimal.ZERO);}
 }
 public record Validation(Long invoiceId,String invoiceNumber,String standard,boolean ready,boolean stored,String contentHash,List<String> errors,String scope) {}
 private final PmsInvoiceRepository invoices;private final PmsInvoiceLineRepository lines;private final HotelPropertyRepository properties;private final PmsPropertyAccessService access;private final PmsInternationalSettingsService international;private final PmsUblSchemaValidator schema;private final PmsAuditWriter audit;private final EntityManager em;
 @Transactional(readOnly=true) public Validation check(String user,Long propertyId,Long invoiceId){PmsInvoice invoice=invoice(user,propertyId,invoiceId,false);PmsStructuredInvoice stored=em.find(PmsStructuredInvoice.class,invoiceId);List<String> errors=new ArrayList<>();try{if(stored==null)generate(invoice,options(invoice,null));else schema.validate(stored.getXmlDocument().getBytes(StandardCharsets.UTF_8),invoice.getType()==InvoiceType.CREDIT_NOTE);}catch(RuntimeException failure){errors.add(failure.getMessage());}return new Validation(invoiceId,invoice.getInvoiceNumber(),"OASIS UBL 2.1",errors.isEmpty(),stored!=null,stored==null?null:stored.getContentHash(),errors,"Offizielles UBL-2.1-XSD, gespeicherte Rechnungsdaten, Pflichtfelder und Betragsabgleich. Keine Peppol-/Landesfreigabe und kein Versand.");}
 public Validation create(String user,Long propertyId,Long invoiceId,Options input){PmsInvoice invoice=invoice(user,propertyId,invoiceId,true);if(em.find(PmsStructuredInvoice.class,invoiceId)==null){if(input==null||input.prepaidAmount()==null)throw bad("Dieser Rechnung zugeordnete Vorauszahlungen ausdrücklich angeben, gegebenenfalls null als Betrag 0.");byte[] xml=generate(invoice,options(invoice,input));PmsStructuredInvoice document=new PmsStructuredInvoice();document.setInvoiceId(invoiceId);document.setXmlDocument(new String(xml,StandardCharsets.UTF_8));document.setContentHash(hash(xml));document.setCreatedAt(LocalDateTime.now(ZoneId.of(invoice.getProperty().getTimezone())));document.setCreatedBy(user);em.persist(document);audit.append(invoice.getProperty(),"invoice.ubl_created","invoice",invoiceId.toString(),"{\"sha256\":\""+document.getContentHash()+"\",\"standard\":\"OASIS-UBL-2.1\"}");em.flush();}return check(user,propertyId,invoiceId);}
 @Transactional(readOnly=true) public byte[] download(String user,Long propertyId,Long invoiceId){invoice(user,propertyId,invoiceId,false);PmsStructuredInvoice stored=em.find(PmsStructuredInvoice.class,invoiceId);if(stored==null)throw bad("Die strukturierte Rechnung zuerst prüfen und erstellen.");return stored.getXmlDocument().getBytes(StandardCharsets.UTF_8);}
 private PmsInvoice invoice(String user,Long propertyId,Long invoiceId,boolean write){var actor=access.access(user);access.require(actor,propertyId,"FINANCE",write);if(write)properties.findByIdAndCompany_IdForUpdate(propertyId,actor.companyId()).orElseThrow(()->bad("Hotel nicht gefunden."));return invoices.findByIdAndProperty_Company_Id(invoiceId,actor.companyId()).filter(i->i.getProperty().getId().equals(propertyId)).orElseThrow(()->bad("Rechnung nicht gefunden."));}
 private Options options(PmsInvoice invoice,Options input){var config=international.settings(invoice.getProperty());return new Options(input!=null&&present(input.zeroTaxCategory())?input.zeroTaxCategory():config.zeroTaxCategory(),input!=null&&present(input.zeroTaxReason())?input.zeroTaxReason():config.zeroTaxReason(),input==null?BigDecimal.ZERO:input.prepaidAmount());}
 byte[] generate(PmsInvoice invoice,Options options){List<PmsInvoiceLine> rows=lines.findAllByInvoice_IdOrderByIdAsc(invoice.getId());BillingProfile seller=PmsProfileData.billing(invoice.getSupplierSnapshot()),buyer=PmsProfileData.billing(invoice.getRecipientSnapshot());
  requireParty(seller,"Gespeicherter Rechnungsaussteller");requireParty(buyer,"Gespeicherter Rechnungsempfänger");if(rows.isEmpty()||invoice.getIssueDate()==null||!present(invoice.getInvoiceNumber()))throw bad("Rechnungsnummer, Datum und Leistungspositionen sind erforderlich.");
  String taxScheme=international.settings(invoice.getProperty()).taxScheme();boolean credit=invoice.getType()==InvoiceType.CREDIT_NOTE;BigDecimal factor=credit?BigDecimal.ONE.negate():BigDecimal.ONE;
  BigDecimal net=BigDecimal.ZERO,tax=BigDecimal.ZERO;for(PmsInvoiceLine line:rows){if(line.getVatRate()==null||line.getQuantity()==null||line.getQuantity().signum()<=0||!present(line.getDescription()))throw bad("Leistungsposition ohne Menge, Beschreibung oder Steuersatz.");if(line.getVatRate().signum()==0)zeroCategory(options);if(line.getNetAmount().add(line.getVatAmount()).compareTo(line.getGrossAmount())!=0)throw bad("Netto- und Steuerbetrag passen nicht zum Bruttobetrag einer Position.");net=net.add(line.getNetAmount());tax=tax.add(line.getVatAmount());}
  if(net.compareTo(invoice.getNetAmount())!=0||tax.compareTo(invoice.getVatAmount())!=0||net.add(tax).compareTo(invoice.getGrossAmount())!=0)throw bad("Rechnungssummen stimmen nicht mit den gespeicherten Leistungspositionen überein.");
  if(net.multiply(factor).signum()<0||invoice.getGrossAmount().multiply(factor).signum()<0)throw bad("Dokumentart und Vorzeichen der Rechnungsbeträge passen nicht zusammen.");
  BigDecimal prepaid=PmsMoney.require(options.prepaidAmount(),invoice.getCurrencyCode());
  if(prepaid.signum()<0||prepaid.compareTo(invoice.getGrossAmount().multiply(factor))>0)throw bad("Zugeordnete Vorauszahlungen müssen zwischen 0 und dem Dokumentbetrag liegen.");
  try{DocumentBuilderFactory factory=DocumentBuilderFactory.newInstance();factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING,true);Document doc=factory.newDocumentBuilder().newDocument();Element root=doc.createElementNS("urn:oasis:names:specification:ubl:schema:xsd:"+(credit?"CreditNote":"Invoice")+"-2",credit?"CreditNote":"Invoice");doc.appendChild(root);root.setAttributeNS(XMLConstants.XMLNS_ATTRIBUTE_NS_URI,"xmlns:cac",CAC);root.setAttributeNS(XMLConstants.XMLNS_ATTRIBUTE_NS_URI,"xmlns:cbc",CBC);
   basic(root,"UBLVersionID","2.1");basic(root,"ID",invoice.getInvoiceNumber());basic(root,"IssueDate",invoice.getIssueDate().toString());if(!credit&&invoice.getDueDate()!=null)basic(root,"DueDate",invoice.getDueDate().toString());basic(root,credit?"CreditNoteTypeCode":"InvoiceTypeCode",credit?"381":"380");if(present(invoice.getCorrectionReason()))basic(root,"Note",invoice.getCorrectionReason());basic(root,"DocumentCurrencyCode",invoice.getCurrencyCode());if(present(buyer.reference()))basic(root,"BuyerReference",buyer.reference());
   if(invoice.getServiceFrom()!=null&&invoice.getServiceTo()!=null){Element period=aggregate(root,"InvoicePeriod");basic(period,"StartDate",invoice.getServiceFrom().toString());basic(period,"EndDate",invoice.getServiceTo().toString());}
   if(credit){if(invoice.getOriginalInvoice()==null)throw bad("Die Gutschrift benötigt die ursprüngliche Rechnungsreferenz.");Element reference=aggregate(aggregate(root,"BillingReference"),"InvoiceDocumentReference");basic(reference,"ID",invoice.getOriginalInvoice().getInvoiceNumber());basic(reference,"IssueDate",invoice.getOriginalInvoice().getIssueDate().toString());}
   party(root,"AccountingSupplierParty",seller,taxScheme,invoice.getSupplierRegistrationNumber());party(root,"AccountingCustomerParty",buyer,taxScheme,null);
   if(present(invoice.getCreditorIban())){Element payment=aggregate(root,"PaymentMeans");basic(payment,"PaymentMeansCode","30");basic(aggregate(payment,"PayeeFinancialAccount"),"ID",invoice.getCreditorIban());}
   Element taxTotal=aggregate(root,"TaxTotal");amount(taxTotal,"TaxAmount",tax.multiply(factor),invoice.getCurrencyCode());Map<BigDecimal,List<PmsInvoiceLine>> buckets=new TreeMap<>();for(var line:rows)buckets.computeIfAbsent(line.getVatRate().stripTrailingZeros(),ignored->new ArrayList<>()).add(line);
   for(var bucket:buckets.entrySet()){Element subtotal=aggregate(taxTotal,"TaxSubtotal");amount(subtotal,"TaxableAmount",bucket.getValue().stream().map(PmsInvoiceLine::getNetAmount).reduce(BigDecimal.ZERO,BigDecimal::add).multiply(factor),invoice.getCurrencyCode());amount(subtotal,"TaxAmount",bucket.getValue().stream().map(PmsInvoiceLine::getVatAmount).reduce(BigDecimal.ZERO,BigDecimal::add).multiply(factor),invoice.getCurrencyCode());category(subtotal,"TaxCategory",bucket.getKey(),options,taxScheme);}
   Element total=aggregate(root,"LegalMonetaryTotal");amount(total,"LineExtensionAmount",net.multiply(factor),invoice.getCurrencyCode());amount(total,"TaxExclusiveAmount",net.multiply(factor),invoice.getCurrencyCode());amount(total,"TaxInclusiveAmount",invoice.getGrossAmount().multiply(factor),invoice.getCurrencyCode());amount(total,"PrepaidAmount",prepaid,invoice.getCurrencyCode());amount(total,"PayableAmount",invoice.getGrossAmount().multiply(factor).subtract(prepaid),invoice.getCurrencyCode());
   int index=0;for(var row:rows){BigDecimal signed=row.getNetAmount().multiply(factor);Element line=aggregate(root,credit?"CreditNoteLine":"InvoiceLine");basic(line,"ID",Integer.toString(++index));Element quantity=basic(line,credit?"CreditedQuantity":"InvoicedQuantity",row.getQuantity().multiply(BigDecimal.valueOf(signed.signum()<0?-1:1)).toPlainString());quantity.setAttribute("unitCode","C62");amount(line,"LineExtensionAmount",signed,invoice.getCurrencyCode());if(row.getServiceDate()!=null){Element period=aggregate(line,"InvoicePeriod");basic(period,"StartDate",row.getServiceDate().toString());basic(period,"EndDate",row.getServiceDate().toString());}Element item=aggregate(line,"Item");basic(item,"Name",row.getDescription());category(item,"ClassifiedTaxCategory",row.getVatRate(),options,taxScheme);Element price=aggregate(line,"Price");amount(price,"PriceAmount",signed.abs().divide(row.getQuantity(),8,RoundingMode.HALF_UP),invoice.getCurrencyCode());}
   TransformerFactory transforms=TransformerFactory.newInstance();transforms.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING,true);transforms.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD,"");transforms.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET,"");Transformer transformer=transforms.newTransformer();transformer.setOutputProperty(OutputKeys.ENCODING,"UTF-8");transformer.setOutputProperty(OutputKeys.INDENT,"yes");ByteArrayOutputStream output=new ByteArrayOutputStream();transformer.transform(new DOMSource(doc),new StreamResult(output));byte[] xml=output.toByteArray();schema.validate(xml,credit);return xml;
  }catch(ResponseStatusException failure){throw failure;}catch(Exception failure){throw bad("Strukturierte Rechnung konnte nicht validiert werden: "+failure.getMessage());}
 }
 private void requireParty(BillingProfile party,String label){if(party==null||!present(party.legalName())||!present(party.addressLine1())||!present(party.city())||!present(party.countryCode())||!Set.of(Locale.getISOCountries()).contains(party.countryCode()))throw bad(label+": Name, Straße, Ort und gültiger ISO-Ländercode fehlen im Rechnungssnapshot.");}
 private void party(Element root,String role,BillingProfile value,String taxScheme,String registration){Element party=aggregate(aggregate(root,role),"Party");basic(aggregate(party,"PartyName"),"Name",value.legalName());Element address=aggregate(party,"PostalAddress");basic(address,"StreetName",value.addressLine1());if(present(value.addressLine2()))basic(address,"AdditionalStreetName",value.addressLine2());basic(address,"CityName",value.city());if(present(value.postalCode()))basic(address,"PostalZone",value.postalCode());if(present(value.region()))basic(address,"CountrySubentity",value.region());basic(aggregate(address,"Country"),"IdentificationCode",value.countryCode());if(present(value.vatNumber())){Element tax=aggregate(party,"PartyTaxScheme");basic(tax,"CompanyID",value.vatNumber());basic(aggregate(tax,"TaxScheme"),"ID",taxScheme);}Element legal=aggregate(party,"PartyLegalEntity");basic(legal,"RegistrationName",value.legalName());if(present(registration))basic(legal,"CompanyID",registration);if(present(value.billingEmail()))basic(aggregate(party,"Contact"),"ElectronicMail",value.billingEmail());}
 private void category(Element parent,String name,BigDecimal rate,Options options,String taxScheme){Element category=aggregate(parent,name);basic(category,"ID",rate.signum()>0?"S":zeroCategory(options));basic(category,"Percent",rate.stripTrailingZeros().toPlainString());if(rate.signum()==0&&present(options.zeroTaxReason()))basic(category,"TaxExemptionReason",options.zeroTaxReason());basic(aggregate(category,"TaxScheme"),"ID",taxScheme);}
 private String zeroCategory(Options options){if(options==null||options.zeroTaxCategory()==null||!Set.of("Z","E","AE","O").contains(options.zeroTaxCategory()))throw bad("Null-Prozent-Leistungen benötigen eine ausdrücklich gewählte Steuerkategorie (Z, E, AE oder O).");if(!options.zeroTaxCategory().equals("Z")&&!present(options.zeroTaxReason()))throw bad("Steuerbefreiung, Reverse Charge oder außerhalb des Steuerbereichs benötigen einen Grund.");return options.zeroTaxCategory();}
 private Element aggregate(Element parent,String name){Element element=parent.getOwnerDocument().createElementNS(CAC,"cac:"+name);parent.appendChild(element);return element;}
 private Element basic(Element parent,String name,String value){Element element=parent.getOwnerDocument().createElementNS(CBC,"cbc:"+name);element.setTextContent(value);parent.appendChild(element);return element;}
 private void amount(Element parent,String name,BigDecimal value,String currency){basic(parent,name,value.stripTrailingZeros().toPlainString()).setAttribute("currencyID",currency);}
 private boolean present(String text){return text!=null&&!text.isBlank();}
 private String hash(byte[] bytes){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}catch(Exception failure){throw new IllegalStateException(failure);}}
 private ResponseStatusException bad(String text){return new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,text);}
}
