// src/context/LanguageContext.jsx
import React, { createContext, useState } from 'react';

const translations = {
    de: {
        // ----------------------------------------------------------------------
        // Login-Bereich
        // ----------------------------------------------------------------------
        login: {
            title: "Willkommen zurück!",
            username: "Benutzername",
            password: "Passwort",
            button: "Login",
            languageLabel: "Sprache",
            error: "Login fehlgeschlagen. Bitte Zugangsdaten prüfen.",
            testStampMessage: "Test-Stempel ausgeführt",
            testStampButton: "Test-Stempel",
            intro: "Melde dich an, um fortzufahren.",
            noAccount: "Noch kein Account?",
            registerHere: "Hier registrieren",
            waitMessage: "Bitte 1 Minute warten, bevor erneut gestempelt wird.",
            stamped: "Eingestempelt",
        },
        // ----------------------------------------------------------------------
        // Admin
        // ----------------------------------------------------------------------
        admin: {
            changePasswordTitle: "Passwort ändern",
            changePasswordButton: "Passwort ändern",
        },
        errors: {
            fetchHolidaysError: "Fehler beim Laden der Feiertage:",
            fetchSickLeaveError: "Fehler beim Laden der Krankmeldungen:",
            userNotLoaded: "Benutzer nicht geladen.",
            unknownError: "Unbekannter Fehler.",
            notLoggedIn: "Nicht eingeloggt.",
            fetchUsersError: "Fehler beim Laden der Benutzer.",
        },
        // ----------------------------------------------------------------------
        // Register
        // ----------------------------------------------------------------------
        register: {
            title: "Registrieren",
            username: "Benutzername",
            password: "Passwort",
            firstName: "Vorname",
            lastName: "Nachname",
            email: "E-Mail",
            button: "Registrieren",
        },
        // ----------------------------------------------------------------------
        // Personal Data
        // ----------------------------------------------------------------------
        personalData: {
            title: "Mein Profil",
            firstName: "Vorname",
            lastName: "Nachname",
            email: "E-Mail",
            emailNotifications: "E-Mail-Benachrichtigungen",
            saveButton: "Speichern",
            saved: "Daten erfolgreich gespeichert.",
            changePassword: "Passwort ändern",
            currentPassword: "Aktuelles Passwort",
            newPassword: "Neues Passwort",
            errorLoading: "Fehler beim Laden der Profildaten",
            errorUpdating: "Fehler beim Aktualisieren des Profils",
            passwordChanged: "Passwort erfolgreich geändert",
            errorChangingPassword: "Fehler beim Ändern des Passworts",
        },
        // ----------------------------------------------------------------------
        // Admin Dashboard
        // ----------------------------------------------------------------------
        adminDashboard: {
            titleWeekly: "Admin-Dashboard (Wochen Ansicht)",
            loggedInAs: "Eingeloggt als",
            adminPassword: "Admin Passwort",
            userPassword: "Benutzerpasswort",
            pleaseEnter: "bitte eingeben",
            timeTrackingCurrentWeek: "Zeiterfassung - Aktuelle Woche",
            prevWeek: "Vorherige Woche",
            nextWeek: "Nächste Woche",
            noEntriesThisWeek: "Keine Einträge in dieser Woche",
            total: "Gesamt",
            hours: "Std",
            minutes: "Min",
            expected: "Soll",
            noValidDate: "Kein gültiges Datum ausgewählt",
            errorApproving: "Fehler beim Genehmigen",
            errorDenying: "Fehler beim Ablehnen",
            editFailed: "Bearbeiten fehlgeschlagen",
            approved: "Genehmigt",
            denied: "Abgelehnt",
            pending: "Offen",
            editButton: "Bearbeiten",
            editTrackingTitle: "Zeiterfassung bearbeiten",
            statusLabel: "Status",
            button: {
                save: "Speichern",
                cancel: "Abbrechen",
                print: "Bericht drucken",
            },
            printButton: "Zeiten drucken",   // de

            vacationRequestsTitle: "Urlaubsanträge (Alle Benutzer)",
            noVacations: "Keine Urlaubsanträge gefunden",
            correctionRequestsTitle: "Korrekturanträge (Alle Benutzer)",
            acceptButton: "Genehmigen",
            rejectButton: "Ablehnen",
            vacationCalendarTitle: "Urlaubskalender",
            forDate: "",
            monthlyOverview: "Monatsübersicht",
            noEntriesThisMonth: "Keine Einträge in diesem Monat",
            startDate: "Startdatum",
            endDate: "Enddatum",
            printReportTitle: "Bericht erstellen",
            searchUser: "Benutzer suchen...",
            noMatch: "Keine passenden Benutzer gefunden.",
            correctionItemLabel: "Korrektur vom",
            noEntries: "Keine Einträge",
            newEntryButton: "Zeiten Eintragen",
            expandAll: "Alle aufklappen",
            collapseAll: "Alle zuklappen",
            correctionApprovedMsg: "Korrektur genehmigt",
            correctionDeniedMsg: "Korrektur abgelehnt",
            correctionErrorMsg: "Fehler bei Korrektur",
            correctionsTitle: "Korrekturanträge",
            correctionModal: {
                approveTitle: "Korrektur genehmigen",
                denyTitle: "Korrektur ablehnen",
                commentLabel: "Kommentar für den Nutzer:",
                commentPlaceholder: "Warum genehmigst / lehnst du ab?",
                confirmButton: "Bestätigen",
            },
        },
        // ----------------------------------------------------------------------
        // User Management
        // ----------------------------------------------------------------------
        userManagement: {
            title: "Benutzerverwaltung",
            newUser: "Neuen Benutzer anlegen",
            editUser: "Benutzer bearbeiten",
            username: "Benutzername",
            firstName: "Vorname",
            lastName: "Nachname",
            address: "Adresse",
            birthDate: "Geburtsdatum",
            entryDate: "Eintrittsdatum",
            country: "Land",
            email: "E-Mail",
            role: "Rolle",
            taxClass: "Steuerklasse",
            tarifCode: "Tarifcode",
            canton: "Kanton",
            civilStatus: "Zivilstand",
            children: "Kinder",
            religion: "Religion",
            healthInsurance: "Krankenkasse",
            bankAccount: "Bankverbindung",
            socialSecurityNumber: "AHV-Nr.",
            personnelNumber: "Personalnummer",
            expectedWorkDays: "Erwartete Arbeitstage",
            breakDuration: "Pausendauer (Min)",
            workPercentage: "Work Percentage",
            annualVacationDays: "Urlaubstage",
            button: {
                save: "Speichern",
                cancel: "Abbrechen",
            },
            table: {
                actions: "Aktionen",
                edit: "Bearbeiten",
                delete: "Löschen",
                programCard: "Karte programmieren",
            },
            scheduleConfig: "Arbeitszeiten Konfiguration",
            cycleLength: "Cycle Length (Wochen):",
            week: "Woche",
            isHourly: "Stundenbasiert:",
            color: "Farbe",
            chooseColor: "Farbe auswählen",
            currentPassword: "Aktuelles Passwort",
            newPassword: "Neues Passwort",
            userPassword: "Benutzerpasswort",
            password: "Passwort",
            errorLoadingUsers: "Fehler beim Laden der Benutzer",
            errorAddingUser: "Fehler beim Anlegen des Benutzers",
            errorUpdatingUser: "Fehler beim Updaten des Benutzers",
            errorDeletingUser: "Fehler beim Löschen des Benutzers",
            programCardSuccess: "Karte erfolgreich programmiert",
            programCardError: "Fehler beim Kartenprogrammieren",
            noUsers: "Keine Benutzer gefunden.",
            errorLoadingTracks: "Fehler beim Laden der Zeiterfassungen",
            errorLoadingVacations: "Fehler beim Laden der Urlaubsanträge",
            errorLoadingCorrections: "Fehler beim Laden der Korrekturanträge",

            // Neue Keys
            percentageTracking: "Prozentbasierte Zeiterfassung",
            deleteConfirmTitle: "Benutzer löschen",
            deleteConfirmMessage: "Soll der Benutzer wirklich gelöscht werden? (Alle Daten werden gelöscht inkl. Zeiten!)",
            nfcProgramStart: "Programmierung gestartet. Bitte Karte auflegen...",
            programCardErrorTimeout: "Zeitüberschreitung beim Kartenprogrammieren.",
            deleteConfirmConfirm: "Ja, löschen",
            deleteConfirmCancel: "Abbrechen",
        },
        // ----------------------------------------------------------------------
        // Navbar
        // ----------------------------------------------------------------------
        navbar: {
            login: "Login",
            register: "Registrieren",
            logout: "Abmelden",
            hi: "Hallo",
            adminStart: "Admin Start",
            userManagement: "Benutzerverwaltung",
            customerManagement: "Kunden",
            projectManagement: "Projekte",
            companyManagement: "Firmen",
            payslips: "Abrechnungen",
            payments: "Zahlungen",
            myDashboard: "Mein Dashboard",
            chatbot: "Chatbot",
            profile: "Profil",
            whatsNew: "Was ist neu?",
            history: "Update-Verlauf",
            brightness: "Helligkeit",
            languageLabel: "Sprache",
        },
        // ----------------------------------------------------------------------
        // Dashboard title / corrections
        // ----------------------------------------------------------------------
        title: "Mein Dashboard",
        correctionRequests: "Korrekturanträge",
        usernameLabel: "Benutzer",
        notLoggedIn: "Nicht eingeloggt",
        expectedWorkHours: "Erwartete Arbeitszeit/Tag",
        diffToday: "Differenz heute",
        overallDiff: "Gesamtdifferenz",
        weekDiff: "Wöchentliche Differenz",
        punchMessage: "Eingestempelt",
        manualPunchTitle: "Manuelles Einstempeln",
        manualPunchButton: "Einstempeln",
        manualPunchMessage: "Manuell eingestempelt",
        manualPunchError: "Fehler beim manuellen Einstempeln",
        noCustomer: "Kein Kunde",
        noProject: "Kein Projekt",
        recentCustomers: "Zuletzt verwendet",
        customerSaved: "Kunde gespeichert",
        customerSaveError: "Fehler beim Speichern des Kunden",
        projectSaveError: "Fehler beim Speichern des Projekts",
        customerLabel: "Kunde",
        projectLabel: "Projekt",
        applyForDay: "Speichern",
        vacationSubmitSuccess: "Urlaubsantrag wurde erfolgreich eingereicht",
        vacationSubmitError: "Fehler beim Einreichen des Urlaubsantrags",
        weeklyOverview: "Wochenübersicht",
        noEntries: "Keine Einträge",
        totalHours: "Gesamtstunden im Monat",
        weekday: "Wochentag",
        date: "Datum",
        workTime: "Arbeitszeit",
        printReportButton: "Zeiten drucken",
        selectPeriod: "Zeitraum auswählen",
        startDate: "Startdatum",
        endDate: "Enddatum",
        cancel: "Abbrechen",
        vacationTitle: "Urlaub beantragen",
        vacationSubmitButton: "Urlaubsantrag absenden",
        myVacations: "Meine Urlaubsanträge",
        to: "bis",
        vacationCalendarTitle: "Urlaubskalender",
        printReportTitle: "Bericht erstellen",
        prevMonth: "Vorheriger Monat",
        nextMonth: "Nächster Monat",
        prevWeek: "Vorherige Woche",
        nextWeek: "Nächste Woche",
        allMonths: "Alle Monate",
        month: "Monat",
        hours: "Std",
        minutes: "Min",
        expected: "Soll",
        remainingVacation: "Verbleibender Urlaub",
        daysLabel: "Tage",
        fullDay: "Ganztags",
        halfDay: "Halbtags",
        days: {
            monday: "Montag",
            tuesday: "Dienstag",
            wednesday: "Mittwoch",
            thursday: "Donnerstag",
            friday: "Freitag",
            saturday: "Samstag",
            sunday: "Sonntag",
        },
        dailyNotePlaceholder: "Tagesnotiz",
        printReportError: "Fehler beim Erstellen des Berichts",
        loading: "Lade...",

        showWeeklyOnly: "Nur aktuelle Woche",
        showAll: "Alle anzeigen",
        workStart: "Work Start",
        breakStart: "Break Start",
        breakEnd: "Break End",
        workEnd: "Work End",
        reason: "Grund",
        submitCorrectionRequest: "Korrektur anfragen",
        submitCorrectionFor: "Korrekturantrag für",
        submitCorrection: "Antrag senden",
        correctionSubmitSuccess: "Korrekturantrag erfolgreich gestellt.",
        correctionSubmitError: "Fehler beim Absenden des Korrekturantrags.",
        errorLoadingProfile: "Fehler beim Laden des Nutzerprofils",
        missingDateRange: "Zeitraum fehlt",
        weekBalance: "Wochensaldo",
        monthBalance: "Monatssaldo",
        overallBalance: "Gesamtsaldo",
        overtimeBalance: "Überstundenkonto",
        overtimeBalanceInfo: "Summe der Überstunden abzüglich genutzter Stunden.",
        noCorrections: "Keine Korrekturanträge vorhanden",
        dailyNoteSaved: "Tagesnotiz gespeichert.",
        dailyNoteError: "Fehler beim Speichern der Tagesnotiz.",
        weeklyHours: "Gesamtstunden (aktuelle Woche)",
        monthlyHours: "Gesamtstunden (Monat)",
        estimatedEarnings: "Gesch\u00e4tzter Verdienst",
        expectedWeekInfo: "Ihr Wochenziel basiert auf Ihrem Arbeitspensum und reduziert sich bei Abwesenheiten.",
        editNotes: "Notizen bearbeiten",
        addNotes: "Notizen hinzufügen",
        fillWorkTimesError: "Bitte Work Start und Work End ausfüllen",

        // fehlende Übersetzungen
        actualTime: "Ist",
        breakTime: "Pause",
        start: "Start",
        end: "Ende",
        worked: "Geleistet",
        pause: "Pause",
        overtime: "Überstunden",
        total: "Gesamt",
        period: "Zeitraum",
        timeReportFor: "Zeitbericht für",
        correctionFor: "Korrektur für",
        welcome: "Willkommen",
        "errors.reportError": "Fehler beim Generieren des Berichts",
        userDashboard: {
            correctionSuccess: "Korrekturantrag erfolgreich eingereicht.",
        },
        adminCorrections: {
            header: {
                user: "Benutzer",
                date: "Antragsdatum",
                request: "Anfrage",
                reason: "Grund",
                status: "Status",
                actions: "Aktionen",
            },
        },
        hourlyDashboard: {
            title: "Stundenbasierte Ansicht",
            mode: "Stundenbasiert",
            addEntryFirst: "Bitte mindestens einen Korrektureintrag hinzufügen.",
            userNotFound: "Benutzer nicht gefunden, bitte erneut anmelden.",
        },

        // ----------------------------------------------------------------------
        // AdminVacation (admin kalendar)
        // ----------------------------------------------------------------------
        adminVacation: {
            title: "Admin Urlaubs Kalender",
            adminPasswordLabel: "Admin-Passwort",
            createVacationButton: "Urlaub erstellen",
            modalTitle: "Urlaub",
            userSelection: "Benutzer Auswahl",
            selectUserPlaceholder: "Bitte Benutzer auswählen",
            startDateLabel: "Startdatum",
            endDateBeforeStart: "Das Enddatum darf nicht vor dem Startdatum liegen.",
            invalidOvertimeHours: "Bitte eine gültige positive Stundenzahl für den Überstundenabzug eingeben.",
            overtimeDeductionHoursLabel: "Abzuziehende Überstunden (in Stunden):",
            hoursPlaceholder: "z.B. 4 oder 8.5",
            usesOvertimeLabel: "Überstunden nutzen",
            halfDayDeductionNotice: "Hinweis: Für diesen halben Tag die entsprechenden Stunden für den halben Tag eintragen.",
            unknownUser: "Unbekannt",
            halfDayShort: "½",
            overtimeVacationShort: "ÜS",
            endDateLabel: "Enddatum",
            halfDayLabel: "Halbtags Urlaub",
            confirmButton: "Bestätigen",
            cancelButton: "Abbrechen",
            noUserSelected: "Bitte einen Benutzer auswählen",
            datesMissing: "Bitte Start- und Enddatum angeben",
            adminPassMissing: "Bitte Admin-Passwort eingeben",
            createdSuccess: "Urlaub erfolgreich (admin) erstellt und direkt genehmigt",
            createError: "Fehler beim Anlegen des Admin-Urlaubs",
            delete: {
                noSelection: "Kein Urlaub zum Löschen ausgewählt.",
                success: "Urlaubsantrag erfolgreich gelöscht.",
                error: "Fehler beim Löschen des Urlaubsantrags:",
                buttonTitle: "Urlaubsantrag löschen",
                confirmTitle: "Urlaub löschen bestätigen",
                confirmMessage: "Möchten Sie den Urlaubsantrag von",
                irreversible: "wirklich unwiderruflich löschen?",
                overtimeReversalInfo: "Bei genehmigten Überstundenurlauben werden die abgezogenen Stunden dem Benutzerkonto wieder gutgeschrieben.",
                regularVacationInfo: "Dies ist ein regulärer Urlaub. Die Tage werden dem Jahresurlaubskonto wieder gutgeschrieben (effektiv durch Neuberechnung der Resturlaubstage).",
                confirmDeleteButton: "Ja, löschen"
            },
        },
        adminCalendar: {
            title: "Admin Kalenderübersicht",
        },
        adminSickLeave: {
            modalTitle: "Krankheit für Benutzer melden",
            userSelection: "Benutzer Auswahl",
            selectUserPlaceholder: "Bitte Benutzer auswählen",
            startDateLabel: "Startdatum",
            endDateLabel: "Enddatum",
            halfDayLabel: "Halbtags krank",
            reportButton: "Krankheit melden",
            reportButtonModal: "Krankmeldung speichern",
            noUserSelected: "Bitte einen Benutzer auswählen",
            datesMissing: "Bitte Start- und Enddatum für die Krankmeldung angeben",
            endDateBeforeStart: "Das Enddatum der Krankheit darf nicht vor dem Startdatum liegen.",
            reportSuccess: "Krankmeldung erfolgreich eingetragen.",
            reportError: "Fehler beim Eintragen der Krankmeldung:",
            unknownUser: "Unbekannt",
            halfDayShort: "½",
        },
        calendarLocale: "de-DE",
        requestVacationButton: "Urlaub beantragen",
        vacationModalTitle: "Urlaubsantrag stellen",
        fromDate: "Von",
        toDate: "Bis",
        dayScope: "Zeitraum",
        vacationType: "Urlaubsart",
        submitButton: "Absenden",
        cancelButton: "Abbrechen",
        comment: "Kommentar (optional)",
        // ----------------------------------------------------------------------
        // vacation (normaler urlaubsflow)
        // ----------------------------------------------------------------------
        vacation: {
            missingDates: "Bitte Start- und Enddatum angeben.",
            invalidDates: "Enddatum darf nicht vor Startdatum liegen.",
            halfDayOneDay: "Halbtags gilt nur für einen einzigen Tag.",
            requestSuccess: "Urlaubsantrag eingereicht.",
            requestError: "Fehler beim Urlaubsantrag.",
            fullDay: "Ganztags",
            halfDay: "Halbtags",
            normalVacation: "Normaler Urlaub",
            overtimeVacation: "Überstundenfrei",
        },
        sickLeave: {
            modalTitle: "Krankheit melden",
            halfDayLabel: "Halbtags",
            commentPlaceholder: "Grund, Arztbesuch etc.",
            fullDay: "Ganztags krank",
            halfDay: "Halbtags krank",
            halfDayOneDay: "Halbtägige Krankmeldung nur für einen Tag.",
            missingDates: "Bitte Start- und Enddatum angeben.",
            invalidDates: "Enddatum darf nicht vor Startdatum liegen.",
            reportButtonShort: "Krank melden",
            reportSuccess: "Krankmeldung eingereicht.",
            reportError: "Fehler beim Einreichen der Krankmeldung.",
            sickShort: "K",
            sick: "Krank",
        },
        // ----------------------------------------------------------------------
        // PrintReport
        // ----------------------------------------------------------------------
        printReport: {
            title: "Zeitenbericht",
            userLabel: "User",
            periodLabel: "Zeitraum",
            summaryWork: "Gesamte Arbeitszeit",
            summaryBreak: "Gesamte Pausenzeit",
            date: "Datum",
            workStart: "Work-Start",
            breakStart: "Break-Start",
            breakEnd: "Break-End",
            workEnd: "Work-End",
            pause: "Pause",
            total: "Arbeit",
            punches: "Stempelungen",
            note: "Notiz",
            overview: "Übersicht",
            worked: "Gearbeitet",
            blocks: "Arbeitsblöcke",
            workLabel: "Arbeit",
            breaks: "Pausen",
            open: "OFFEN",
            noEntries: "Keine Einträge",
            printButton: "Drucken",
            pdfButton: "PDF speichern",
        },
        // ----------------------------------------------------------------------
        // Landing Page
        // ----------------------------------------------------------------------
        landingPage: {
            headline: "Chrono-Logisch",
            subHeadline: "Zeiterfassung und NFC-Stempeln – ganz einfach.",
            loginButton: "Anmelden",
            registerButton: "Registrieren",
            whyTitle: "Warum Chrono-Logisch?",
            howItWorks: "So funktioniert's",
            featureNfcTitle: "NFC-Stempeln",
            featureNfcText: "Einfaches Ein- und Ausstempeln per NFC-Karte.",
            featureReportsTitle: "Automatische Berichte",
            featureReportsText: "Übersichtliche Auswertungen und PDF-Exports.",
            featureVacationTitle: "Urlaubsverwaltung",
            featureVacationText: "Urlaubstage im Blick, inkl. Genehmigungsprozess.",
            allRights: "Alle Rechte vorbehalten.",
            infoText: "Chrono-Logisch erkennt automatisch den richtigen Stempel, verhindert Dubletten und füllt vergessene Punch-Outs von selbst.",
            featuresTitle: "Alle Funktionen im Überblick",
            featuresSub: "Keine Gimmicks – nur Features, die deinen Alltag wirklich erleichtern.",
            ctaPrimary: "Kostenlos registrieren",
            featureSmartTitle: "Smart Punch",
            featureSmartText: "Erkennt automatisch Work Start, Break Start/End & Work End.",
            featureDirectTitle: "Direkter Punch",
            featureDirectText: "Vier feste Status gezielt wählbar – Übergangs-Logik inklusive.",
            featureDuplicateTitle: "Duplicate-Schutz",
            featureDuplicateText: "Einzigartiger DB-Index + Catch-Up-Logik verhindern Doppel-Clicks.",
            featureAutoPunchOutTitle: "Auto Punch Out",
            featureAutoPunchOutText: "Cron-Job 23:20 Uhr beendet vergessene Stempel automatisch.",
            featurePercentTitle: "Prozent-Punch",
            featurePercentText: "Teilzeit gibt Tages-% an – Ist/Soll-Delta sofort berechnet.",
            featureAdminTitle: "Korrekturen & Admin",
            featureAdminText: "Einträge editieren, ganzen Tag neu schreiben oder Notizen setzen.",
            featureHistoryTitle: "Berichte & Historie",
            featureHistoryText: "Tages-, Wochen-, Bereichs-Reports + vollständige Nutzer-History.",
            featureOvertimeTitle: "Überstunden-Mgmt",
            featureOvertimeText: "Persönliche Minuten-Balance auto-aktualisiert, Urlaub einbezogen.",
            stepsTitle: "In 3 Schritten startklar",
            step1Title: "Account anlegen",
            step1Text: "Firmen-Profil & Teams in wenigen Minuten.",
            step2Title: "NFC-Badges koppeln",
            step2Text: "Einmalig scannen, fertig.",
            step3Title: "Dashboard nutzen",
            step3Text: "Echtzeit-Insights & Abwesenheiten verwalten.",
            newsletterTitle: "Bleib informiert!",
            newsletterText: "Updates & Tipps direkt in dein Postfach.",
            newsletterPlaceholder: "Deine E-Mail",
            newsletterButton: "Abonnieren",
            contactTitle: "Kontakt",
            contactName: "Name",
            contactEmail: "E-Mail",
            contactMessage: "Nachricht",
            contactButton: "Absenden",
            contactSuccess: "Nachricht gesendet!",
            contactError: "Fehler beim Senden.",
        },

        // Falls du "search", "darkMode", "lightMode" usw. nutzt
        search: "Suchen",
        darkMode: "Dark Mode",
        lightMode: "Light Mode",
        page: "Seite",
        of: "von",
        for: "für",
        ok: "OK",
        done: "Erledigt",
        sessionExpired: "Session abgelaufen. Bitte erneut einloggen.",
        impressum: "Impressum",
        agb: "AGB",
        instagram: "Instagram",
        changelogModal: {
            whatsNew: "Was ist neu in Version",
            published: "Veröffentlicht am",
            close: "Schließen",
        },
        whatsNewPage: {
            title: "Alle Änderungen und Updates",
            loading: "Lade Verlauf...",
        },
        payslips: {
            title: "Meine Gehaltsabrechnungen",
            pendingTitle: "Offene Gehaltsabrechnungen",
            approvedTitle: "Freigegebene Gehaltsabrechnungen",
            approve: "Freigeben",
            approveAll: "Alle freigeben",
            exportCsv: "CSV Export",
            backup: "Backup",
            print: "Drucken",
            period: "Zeitraum",
            user: "Benutzer",
            gross: "Brutto",
            net: "Netto",
            payoutDate: "Auszahlungsdatum",
            filterName: "Name",
            start: "Startdatum",
            end: "Enddatum",
            filter: "Filtern",
            printError: "PDF konnte nicht geladen werden",
            saveLogo: "Logo speichern",
            logoSaved: "Logo gespeichert",
            logoSaveError: "Fehler beim Speichern",
            scheduleDay: "Automatisch am Tag",
            scheduleButton: "Planen",
            scheduleAll: "Automatische Abrechnung für alle aktivieren",
            editPayout: "Datum ändern",
            enterPayoutDate: "Auszahlungsdatum eingeben",
            generateManual: "Manuell erstellen",
            selectUser: "Benutzer wählen",
            generate: "Erstellen",
            logoUploadTitle: "Logo hochladen",
            selectFile: "Datei wählen",
            myPayslips: "Meine Lohnabrechnungen"


        },
        quickStart: {
            title: "Quick Start",
            profile: "Profil ausfüllen",
            punch: "Erste Zeiterfassung",
            vacation: "Urlaub beantragen",
            progress: "erledigt",
        },
        impressumPage: {
            title: "Impressum",
            address: "<strong>Chrono-Logisch</strong><br />Einzelunternehmen<br />Inhaber: Christopher Siefert<br />Lettenstrasse 20<br />CH-9122 Mogelsberg",
            contact: "Telefon: <a href=\"tel:+41765467960\">+41 76 546 79 60</a><br />E-Mail: <a href=\"mailto:siefertchristopher@chrono-logisch.ch\">siefertchristopher@chrono-logisch.ch</a>",
            responsible: "Verantwortlich für den Inhalt dieser Website: <br />Christopher Siefert (Inhaber)",
            liability: "<strong>Haftungsausschluss:</strong><br />Für die Inhalte externer Links übernehmen wir keine Haftung. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.",
            copyright: "<strong>Copyright:</strong><br />Sämtliche Inhalte (Texte, Bilder, Grafiken) auf dieser Website sind urheberrechtlich geschützt. Jegliche Nutzung ohne ausdrückliche Zustimmung ist untersagt.",
            stand: "<em>Stand: Mai 2025</em>",
        },
        agbPage: {
            title: "Allgemeine Geschäftsbedingungen",
            intro1: "Diese Allgemeinen Geschäftsbedingungen (AGB) gelten für alle Verträge zwischen Chrono-Logisch und dem Kunden.",
            intro2: "Der Anbieter stellt dem Kunden eine Zeiterfassungs-App zur Verfügung. Der genaue Funktionsumfang ergibt sich aus den Informationen auf der Website.",
            intro3: "Ein Vertrag kommt zustande, sobald der Kunde ein Paket bucht und der Anbieter dies bestätigt.",
            stand: "Stand Mai 2025",
        },
        registrationPage: {
            pricingTitle: "Pakete & Preisübersicht",
            pricingIntro: "Wählen Sie das Paket, das am besten passt.",
            monthlyBilling: "Monatliche Zahlung",
            yearlyBilling: "Jährliche Zahlung (2 Monate geschenkt!)",
            employeeCount: "Anzahl Mitarbeiter (1-100):",
            trainingTitle: "Optionales Add-on:",
            addTraining: "Zusätzliches Intensiv-Onboarding (1 Std. individuell)",
            footnote: "Alle Preise zzgl. MwSt.",
            sendRequest: "Registrierungsanfrage senden",
            sending: "Anfrage wird gesendet...",
            thanks: "Vielen Dank für Ihre Anfrage!",
            backHome: "Zurück zur Startseite"

        },
        notFound: {
            pageNotFound: "404 - Seite nicht gefunden",
        },


    },

    // =============== ENGLISCH ===============
    en: {
        // ----------------------------------------------------------------------
        // Login
        // ----------------------------------------------------------------------
        login: {
            title: "Welcome Back!",
            username: "Username",
            password: "Password",
            button: "Log in",
            languageLabel: "Language",
            error: "Login failed. Please check your credentials.",
            testStampMessage: "Test stamp executed",
            testStampButton: "Test Stamp",
            intro: "Sign in to continue.",
            noAccount: "No account yet?",
            registerHere: "Register here",
            waitMessage: "Please wait 1 minute before stamping again.",
            stamped: "Stamped",
        },
        // ----------------------------------------------------------------------
        // Admin
        // ----------------------------------------------------------------------
        admin: {
            changePasswordTitle: "Change Password",
            changePasswordButton: "Change Password",
        },
        errors: {
            fetchHolidaysError: "Error loading holidays:",
            fetchSickLeaveError: "Error loading sick leaves:",
            userNotLoaded: "User not loaded.",
            unknownError: "Unknown error.",
            notLoggedIn: "Not logged in.",
            fetchUsersError: "Error loading users.",
        },
        // ----------------------------------------------------------------------
        // Register
        // ----------------------------------------------------------------------
        register: {
            title: "Register",
            username: "Username",
            password: "Password",
            firstName: "First Name",
            lastName: "Last Name",
            email: "Email",
            button: "Register",
        },
        // ----------------------------------------------------------------------
        // Personal Data
        // ----------------------------------------------------------------------
        personalData: {
            title: "My Profile",
            firstName: "First Name",
            lastName: "Last Name",
            email: "Email",
            emailNotifications: "Email Notifications",
            saveButton: "Save",
            saved: "Data saved successfully.",
            changePassword: "Change Password",
            currentPassword: "Current Password",
            newPassword: "New Password",
            errorLoading: "Error loading profile data",
            errorUpdating: "Error updating profile",
            passwordChanged: "Password changed successfully",
            errorChangingPassword: "Error changing password",
        },
        // ----------------------------------------------------------------------
        // Admin Dashboard
        // ----------------------------------------------------------------------
        adminDashboard: {
            titleWeekly: "Admin Dashboard (Weekly View)",
            loggedInAs: "Logged in as",
            adminPassword: "Admin Password",
            userPassword: "User Password",
            pleaseEnter: "please enter",
            timeTrackingCurrentWeek: "Time Tracking - Current Week",
            prevWeek: "Previous Week",
            nextWeek: "Next Week",
            noEntriesThisWeek: "No entries for this week",
            total: "Total",
            hours: "hrs",
            minutes: "min",
            expected: "Expected",
            noValidDate: "No valid date selected",
            errorApproving: "Error approving",
            errorDenying: "Error denying",
            editFailed: "Edit failed",
            approved: "Approved",
            denied: "Denied",
            pending: "Pending",
            editButton: "Edit",
            editTrackingTitle: "Edit Time Tracking",
            statusLabel: "Status",
            button: {
                save: "Save",
                cancel: "Cancel",
                print: "Print Report",
            },
            printButton: "Print times",      // en
            vacationRequestsTitle: "Vacation Requests (All Users)",
            noVacations: "No vacation requests found",
            correctionRequestsTitle: "Correction Requests (All Users)",
            acceptButton: "Approve",
            rejectButton: "Reject",
            vacationCalendarTitle: "Vacation Calendar",
            forDate: "",
            monthlyOverview: "Monthly Overview",
            noEntriesThisMonth: "No entries for this month",
            startDate: "Start Date",
            endDate: "End Date",
            printReportTitle: "Generate Report",
            searchUser: "Search user...",
            noMatch: "No matching users found.",
            correctionItemLabel: "Correction for",
            noEntries: "No entries",
            newEntryButton: "Add Times",
            expandAll: "Expand All",
            collapseAll: "Collapse All",
            correctionApprovedMsg: "Correction approved",
            correctionDeniedMsg: "Correction denied",
            correctionErrorMsg: "Error during correction",
            correctionsTitle: "Correction Requests",
            correctionModal: {
                approveTitle: "Approve Correction",
                denyTitle: "Deny Correction",
                commentLabel: "Comment for the user:",
                commentPlaceholder: "Why approve or deny?",
                confirmButton: "Confirm",
            },
        },
        // ----------------------------------------------------------------------
        // User Management
        // ----------------------------------------------------------------------
        userManagement: {
            title: "User Management",
            newUser: "Create New User",
            editUser: "Edit User",
            username: "Username",
            firstName: "First Name",
            lastName: "Last Name",
            address: "Address",
            birthDate: "Birth Date",
            entryDate: "Entry Date",
            country: "Country",
            email: "Email",
            role: "Role",
            taxClass: "Tax Class",
            tarifCode: "Tariff Code",
            canton: "Canton",
            civilStatus: "Civil Status",
            children: "Children",
            religion: "Religion",
            healthInsurance: "Health Insurance",
            bankAccount: "Bank Account",
            socialSecurityNumber: "Social Security Number",
            personnelNumber: "Personnel Number",
            expectedWorkDays: "Expected Work Days",
            breakDuration: "Break Duration (min)",
            workPercentage: "Work Percentage",
            annualVacationDays: "Vacation Days",
            button: {
                save: "Save",
                cancel: "Cancel",
            },
            table: {
                actions: "Actions",
                edit: "Edit",
                delete: "Delete",
                programCard: "Program Card",
            },
            scheduleConfig: "Work Hours Configuration",
            cycleLength: "Cycle Length (Weeks):",
            week: "Week",
            isHourly: "Hourly:",
            color: "Color",
            chooseColor: "Choose Color",
            currentPassword: "Current Password",
            newPassword: "New Password",
            userPassword: "User Password",
            password: "Password",
            errorLoadingUsers: "Error loading users",
            errorAddingUser: "Error adding user",
            errorUpdatingUser: "Error updating user",
            errorDeletingUser: "Error deleting user",
            programCardSuccess: "Card successfully programmed",
            programCardError: "Error programming card",
            noUsers: "No users found.",
            errorLoadingTracks: "Error loading time entries",
            errorLoadingVacations: "Error loading vacation requests",
            errorLoadingCorrections: "Error loading correction requests",

            percentageTracking: "Percentage-based tracking",
            deleteConfirmTitle: "Delete User",
            deleteConfirmMessage: "Do you really want to delete this user? (All data including times will be removed!)",
            nfcProgramStart: "Programming started. Please place the card...",
            programCardErrorTimeout: "Timeout while programming the card.",
            deleteConfirmConfirm: "Yes, delete",
            deleteConfirmCancel: "Cancel",
        },
        // ----------------------------------------------------------------------
        // Navbar
        // ----------------------------------------------------------------------
        navbar: {
            login: "Login",
            register: "Register",
            logout: "Logout",
            hi: "Hi",
            adminStart: "Admin Start",
            userManagement: "User Management",
            customerManagement: "Customers",
            projectManagement: "Projects",
            companyManagement: "Companies",
            payslips: "Payslips",
            payments: "Payments",
            myDashboard: "My Dashboard",
            chatbot: "Chatbot",
            profile: "Profile",
            whatsNew: "What's New?",
            history: "Update History",
            brightness: "brightness",
            languageLabel: "Language",
        },
        // ----------------------------------------------------------------------
        // Dashboard / corrections
        // ----------------------------------------------------------------------
        title: "My Dashboard",
        correctionRequests: "Correction Requests",
        usernameLabel: "User",
        notLoggedIn: "Not logged in",
        expectedWorkHours: "Expected Work Hours per Day",
        diffToday: "Difference Today",
        overallDiff: "Overall Difference",
        weekDiff: "Weekly Difference",
        punchMessage: "Stamped",
        manualPunchTitle: "Manual Stamping",
        manualPunchButton: "Stamp",
        manualPunchMessage: "Manually stamped",
        manualPunchError: "Error during manual stamping",
        noCustomer: "No customer",
        noProject: "No project",
        recentCustomers: "Recent customers",
        customerSaved: "Customer saved",
        customerSaveError: "Error saving customer",
        projectSaveError: "Error saving project",
        customerLabel: "Customer",
        projectLabel: "Project",
        applyForDay: "Save",
        vacationSubmitSuccess: "Vacation request submitted successfully",
        vacationSubmitError: "Error submitting vacation request",
        weeklyOverview: "Weekly Overview",
        noEntries: "No entries",
        totalHours: "Total Hours in Month",
        weekday: "Weekday",
        date: "Date",
        workTime: "Work Time",
        printReportButton: "Print Times",
        selectPeriod: "Select Period",
        startDate: "Start Date",
        endDate: "End Date",
        cancel: "Cancel",
        vacationTitle: "Request Vacation",
        vacationSubmitButton: "Submit Vacation Request",
        myVacations: "My Vacation Requests",
        to: "to",
        vacationCalendarTitle: "Vacation Calendar",
        printReportTitle: "Generate Report",
        prevMonth: "Previous Month",
        nextMonth: "Next Month",
        prevWeek: "Previous Week",
        nextWeek: "Next Week",
        allMonths: "All Months",
        month: "Month",
        hours: "hrs",
        minutes: "min",
        expected: "Expected",
        remainingVacation: "Remaining Vacation",
        daysLabel: "days",
        fullDay: "Full Day",
        halfDay: "Half Day",
        days: {
            monday: "Monday",
            tuesday: "Tuesday",
            wednesday: "Wednesday",
            thursday: "Thursday",
            friday: "Friday",
            saturday: "Saturday",
            sunday: "Sunday",
        },

        dailyNotePlaceholder: "Daily note",
        printReportError: "Error generating report",
        loading: "Loading...",

        showWeeklyOnly: "Show current week only",
        showAll: "Show all",
        workStart: "Work Start",
        breakStart: "Break Start",
        breakEnd: "Break End",
        workEnd: "Work End",
        reason: "Reason",
        submitCorrectionRequest: "Request Correction",
        submitCorrectionFor: "Correction request for",
        submitCorrection: "Submit request",
        correctionSubmitSuccess: "Correction request submitted successfully.",
        correctionSubmitError: "Error submitting correction request.",
        errorLoadingProfile: "Error loading user profile",
        missingDateRange: "Date range missing",
        weekBalance: "Weekly Balance",
        monthBalance: "Monthly Balance",
        overallBalance: "Total Balance",
        overtimeBalance: "Overtime Balance",
        noCorrections: "No correction requests found",
        dailyNoteSaved: "Daily note saved.",
        overtimeBalanceInfo: "Total overtime minus used or deducted hours.",
        dailyNoteError: "Error saving daily note.",
        weeklyHours: "Total hours (current week)",
        monthlyHours: "Total hours (month)",
        estimatedEarnings: "Estimated earnings",
        editNotes: "Edit notes",
        expectedWeekInfo: "Your weekly target is based on your work percentage and reduces when you are absent.",
        addNotes: "Add notes",
        fillWorkTimesError: "Please fill in Work Start and Work End",

        // missing translations
        actualTime: "Actual",
        breakTime: "Break Time",
        start: "Start",
        end: "End",
        worked: "Worked",
        pause: "Break",
        overtime: "Overtime",
        total: "Total",
        period: "Period",
        timeReportFor: "Time report for",
        correctionFor: "Correction for",
        welcome: "Welcome",
        "errors.reportError": "Error generating report",
        userDashboard: {
            correctionSuccess: "Correction request submitted successfully.",
        },
        adminCorrections: {
            header: {
                user: "User",
                date: "Request Date",
                request: "Request",
                reason: "Reason",
                status: "Status",
                actions: "Actions",
            },
        },

        // ----------------------------------------------------------------------
        // AdminVacation
        // ----------------------------------------------------------------------
        adminVacation: {
            title: "Admin Vacation Calendar",
            adminPasswordLabel: "Admin Password",
            createVacationButton: "Create Vacation",
            modalTitle: "Vacation",
            userSelection: "Select User",
            selectUserPlaceholder: "Please select user",
            startDateLabel: "Start Date",
            endDateLabel: "End Date",
            halfDayLabel: "Half-day Vacation",
            confirmButton: "Confirm",
            cancelButton: "Cancel",
            noUserSelected: "Please select a user",
            datesMissing: "Please provide start and end dates",
            adminPassMissing: "Please enter admin password",
            createdSuccess: "Vacation created (admin) and approved",
            createError: "Error creating admin vacation",
            endDateBeforeStart: "End date cannot be before start date.",
            invalidOvertimeHours: "Please enter a valid positive number of hours for overtime deduction.",
            overtimeDeductionHoursLabel: "Overtime deduction overall (hours):",
            hoursPlaceholder: "e.g. 4 or 8.5",
            usesOvertimeLabel: "Use overtime",
            halfDayDeductionNotice: "Note: enter the hours for the half day.",
            unknownUser: "Unknown",
            halfDayShort: "1/2",
            overtimeVacationShort: "OT",
            delete: {
                noSelection: "No vacation selected to delete.",
                success: "Vacation request deleted successfully.",
                error: "Error deleting vacation request:",
                buttonTitle: "Delete vacation request",
                confirmTitle: "Confirm delete vacation",
                confirmMessage: "Do you want to delete the vacation of",
                irreversible: "permanently delete?",
                overtimeReversalInfo: "For approved overtime vacations the deducted hours will be restored.",
                regularVacationInfo: "This is a regular vacation. The days will be credited back to annual vacation balance.",
                confirmDeleteButton: "Yes, delete"
            },
        },
        adminCalendar: {
            title: "Admin Calendar Overview",
        },
        adminSickLeave: {
            modalTitle: "Report Sick Leave",
            userSelection: "Select User",
            selectUserPlaceholder: "Please select user",
            startDateLabel: "Start Date",
            endDateLabel: "End Date",
            halfDayLabel: "Half-day Sick",
            reportButton: "Report Sick",
            reportButtonModal: "Save Sick Leave",
            noUserSelected: "Please select a user",
            datesMissing: "Please provide start and end dates",
            endDateBeforeStart: "End date cannot be before start date.",
            reportSuccess: "Sick leave reported successfully.",
            reportError: "Error reporting sick leave:",
            unknownUser: "Unknown",
            halfDayShort: "1/2",
        },
        // ----------------------------------------------------------------------
        // Vacation
        // ----------------------------------------------------------------------
        vacation: {
            missingDates: "Please provide start and end date.",
            invalidDates: "End date cannot be before start date.",
            halfDayOneDay: "Half-day only valid for a single day.",
            requestSuccess: "Vacation request submitted.",
            requestError: "Error submitting vacation request.",
            fullDay: "Full day",
            halfDay: "Half day",
            normalVacation: "Normal vacation",
            overtimeVacation: "Overtime-based",
        },
        sickLeave: {
            modalTitle: "Report Sick Leave",
            halfDayLabel: "Half-day",
            commentPlaceholder: "Reason, doctor visit etc.",
            fullDay: "Full-day sick",
            halfDay: "Half-day sick",
            halfDayOneDay: "Half-day sick leave only for one day.",
            missingDates: "Please provide start and end dates.",
            invalidDates: "End date cannot be before start date.",
            reportButtonShort: "Report Sick",
            reportSuccess: "Sick leave submitted.",
            reportError: "Error submitting sick leave.",
            sickShort: "S",
            sick: "Sick",
        },
        calendarLocale: "en-US",
        requestVacationButton: "Request Vacation",
        vacationModalTitle: "Submit Vacation Request",
        fromDate: "From",
        toDate: "To",
        dayScope: "Period",
        vacationType: "Vacation Type",
        submitButton: "Submit",
        cancelButton: "Cancel",
        comment: "Comment (optional)",
        // ----------------------------------------------------------------------
        // PrintReport
        // ----------------------------------------------------------------------
        printReport: {
            title: "Time Report",
            userLabel: "User",
            periodLabel: "Period",
            summaryWork: "Total Work Time",
            summaryBreak: "Total Break Time",
            date: "Date",
            workStart: "Work Start",
            breakStart: "Break Start",
            breakEnd: "Break End",
            workEnd: "Work End",
            pause: "Break",
            total: "Work",
            punches: "Punches",
            note: "Note",
            overview: "Overview",
            worked: "Worked",
            blocks: "Work Blocks",
            workLabel: "Work",
            breaks: "Breaks",
            open: "OPEN",
            noEntries: "No entries",
            printButton: "Print",
            pdfButton: "Save PDF",
        },
        // ----------------------------------------------------------------------
        // Landing Page
        // ----------------------------------------------------------------------
        landingPage: {
            headline: "Chrono-Logisch",
            subHeadline: "Time tracking and NFC stamping made easy.",
            ctaPrimary: "Register for free",
            loginButton: "Login",
            registerButton: "Register",
            whyTitle: "Why Chrono-Logisch?",
            howItWorks: "How it Works",
            featureNfcTitle: "NFC Stamping",
            infoText: "Chrono-Logisch automatically detects the correct punch, avoids duplicates and fills forgotten outs overnight.",
            featuresTitle: "All Features at a Glance",
            featuresSub: "No gimmicks – just features that really ease your day.",
            featureNfcText: "Simply clock in and out with an NFC card.",
            featureReportsTitle: "Automatic Reports",
            featureReportsText: "Clear evaluations and PDF exports.",
            featureVacationTitle: "Vacation Management",
            featureVacationText: "Keep track of vacation days, including approval workflow.",
            allRights: "All rights reserved.",
            featureSmartTitle: "Smart Punch",
            featureSmartText: "Automatically detects Work Start, Break Start/End and Work End.",
            featureDirectTitle: "Direct Punch",
            featureDirectText: "Four fixed statuses selectable with transition logic.",
            featureDuplicateTitle: "Duplicate Protection",
            featureDuplicateText: "Unique DB index and catch-up logic prevent double clicks.",
            featureAutoPunchOutTitle: "Auto Punch Out",
            featureAutoPunchOutText: "Cron job 23:20 ends forgotten punches automatically.",
            featurePercentTitle: "Percent Punch",
            featurePercentText: "Part time enters daily % – instant actual/target delta.",
            featureAdminTitle: "Corrections & Admin",
            featureAdminText: "Edit entries, rewrite whole days or add notes.",
            featureHistoryTitle: "Reports & History",
            featureHistoryText: "Daily, weekly, area reports plus full user history.",
            featureOvertimeTitle: "Overtime Mgmt",
            featureOvertimeText: "Personal minute balance auto updated, vacation included.",
            stepsTitle: "Ready in 3 steps",
            step1Title: "Create Account",
            step1Text: "Company profile & teams in minutes.",
            step2Title: "Link NFC badges",
            step2Text: "Scan once, done.",
            step3Title: "Use Dashboard",
            step3Text: "Realtime insights & absence management.",
            newsletterTitle: "Stay informed!",
            newsletterText: "Updates and tips straight to your inbox.",
            newsletterPlaceholder: "Your email",
            newsletterButton: "Subscribe",
            contactTitle: "Contact",
            contactName: "Name",
            contactEmail: "Email",
            contactMessage: "Message",
            contactButton: "Send",
            contactSuccess: "Message sent!",
            contactError: "Failed to send message.",
        },

        // Falls du "search", "darkMode", "lightMode" etc. nutzt
        search: "Search",
        darkMode: "Dark Mode",
        lightMode: "Light Mode",
        page: "Page",
        of: "of",
        for: "for",
        ok: "OK",
        done: "Done",
        sessionExpired: "Session expired. Please log in again.",
        impressum: "Impressum",
        agb: "Terms",
        instagram: "Instagram",
        changelogModal: {
            whatsNew: "What's new in version",
            published: "Published on",
            close: "Close",
        },
        whatsNewPage: {
            title: "All changes and updates",
            loading: "Loading history...",
        },
        payslips: {
            title: "My Payslips",
            pendingTitle: "Pending Payslips",
            approvedTitle: "Approved Payslips",
            approve: "Approve",
            approveAll: "Approve All",
            exportCsv: "CSV Export",
            backup: "Backup",
            print: "Print",
            period: "Period",
            user: "User",
            gross: "Gross",
            net: "Net",
            payoutDate: "Payout date",
            filterName: "Name",
            start: "Start",
            end: "End",
            filter: "Filter",
            printError: "Failed to load PDF",
            saveLogo: "Save logo",
            logoSaved: "Logo saved",
            logoSaveError: "Failed to save logo",
            scheduleDay: "Automatically on day",
            scheduleButton: "Schedule",
            scheduleAll: "Enable automatic payslips for all",
            editPayout: "Edit date",
            enterPayoutDate: "Enter payout date",
            generateManual: "Generate manually",
            selectUser: "Select user",
            generate: "Generate",
            logoUploadTitle: "Upload logo",
            selectFile: "Choose file",
            myPayslips: "My Payslips"


        },
        quickStart: {
            title: "Quick Start",
            profile: "Complete your profile",
            punch: "First time tracking",
            vacation: "Request vacation",
            progress: "done",
        },
        impressumPage: {
            title: "Imprint",
            address: "<strong>Chrono-Logisch</strong><br />Sole proprietorship<br />Owner: Christopher Siefert<br />Lettenstrasse 20<br />CH-9122 Mogelsberg",
            contact: "Phone: <a href=\"tel:+41765467960\">+41 76 546 79 60</a><br />Email: <a href=\"mailto:siefertchristopher@chrono-logisch.ch\">siefertchristopher@chrono-logisch.ch</a>",
            responsible: "Responsible for this website:<br />Christopher Siefert (owner)",
            liability: "<strong>Disclaimer:</strong><br />We assume no liability for the content of external links. The operators of the linked pages are solely responsible for their content.",
            copyright: "<strong>Copyright:</strong><br />All content on this website is protected by copyright. Any use without explicit permission is prohibited.",
            stand: "<em>Updated: May 2025</em>",
        },
        agbPage: {
            title: "Terms of Service",
            intro1: "These terms of service govern all contracts between Chrono-Logisch and the customer.",
            intro2: "The provider makes a time tracking app available. Details of the functionality are described on the website.",
            intro3: "A contract is formed once the customer books a package and the provider confirms it.",
            stand: "Updated May 2025",
        },
        registrationPage: {
            pricingTitle: "Packages & Pricing",
            pricingIntro: "Choose the package that fits best.",
            monthlyBilling: "Monthly billing",
            yearlyBilling: "Yearly billing (2 months free!)",
            employeeCount: "Number of employees (1-100):",
            trainingTitle: "Optional add-on:",
            addTraining: "Additional intensive onboarding (1h)",
            footnote: "All prices excl. VAT.",
            sendRequest: "Send registration request",
            sending: "Sending request...",
            thanks: "Thank you for your request!",
            backHome: "Back to homepage"
        },
        notFound: {
            pageNotFound: "404 - Page not found",
        },
        hourlyDashboard: {
            addEntryFirst: "Please add at least one correction entry.",
            userNotFound: "User not found, please log in again.",
        },
    },
};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    // Standard: "de" oder "en" je nach Vorliebe
    const [language, setLanguage] = useState("de");

    /**
     * @param {string} key     z.B. "login.title"
     * @param {string} fallback (optional) Fallback-Text, wenn Key fehlt
     */
    const t = (key, fallback) => {
        const keys = key.split(".");
        let translation = translations[language];
        for (const k of keys) {
            if (translation[k] !== undefined) {
                translation = translation[k];
            } else {
                return fallback || key; // Falls gewünscht
            }
        }
        if (typeof translation === "object") {
            console.warn(
                `Translation for key "${key}" is an object. Expected a string.`
            );
            return JSON.stringify(translation);
        }
        return translation;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => {
    const { t } = React.useContext(LanguageContext);
    return { t };
};
